name: cargo cache

description: Cache rust dependencies to github or local

inputs:
  key:
    required: true
  save-if:
    default: false
    required: false
    type: boolean

runs:
  using: composite
  steps:
    - name: Cache to github
      if: ${{ runner.environment == 'github-hosted' }}
      uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      with:
        prefix-key: 'RCache-G-2'
        shared-key: ${{ inputs.key }}
        save-if: ${{ inputs.save-if }}
        cache-workspace-crates: 'true'
        cache-all-crates: 'true'

    - name: Cache to local
      uses: rstackjs/rust-cache@63150d5565b253e99497cbe4226561b3297fd0dc # feat/cache-workspace-crates
      if: ${{ runner.environment == 'self-hosted' }}
      with:
        prefix-key: 'RCache-L-6-test1'
        shared-key: ${{ inputs.key }}
        save-if: ${{ inputs.save-if }}
        fullmatch-only: 'true'
        cache-workspace-crates: 'true'
        cache-all-crates: 'true'
