packages:
  - 'packages/*'
  - 'examples/*'
  - 'scripts'
  - 'website'
  - 'tests/e2e/fixtures/**'
  - 'npm/*'
  - 'crates/node_binding'
  - 'crates/rspack_binding_builder_testing'
  - 'tests/e2e'
  - 'tests/e2e-browser'
  - 'tests/rspack-test'
  - 'tests/type-tests'
  - 'tests/bench'
  # this following is used to test resolve in monorepo
  - 'tests/rspack-test/normalCases/resolve/pnpm-workspace/packages/*'

allowBuilds:
  '@parcel/watcher': false
  core-js: false
  'es5-ext': false
  'esbuild': true

dedupePeers: true

autoInstallPeers: false

peerDependencyRules:
  ignoreMissing:
    - webpack
    - '@algolia/client-search'
    - algoliasearch
    - search-insights

# Reduce the risk of installing compromised packages
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@rspack/*'
  - '@rsbuild/*'
  - '@rslib/*'
  - '@rspress/*'
  - '@rstest/*'
  - '@rsdoctor/*'
  - '@rslint/*'
  - '@rstack-dev/doc-ui'
  - 'rsbuild-plugin-*'
  - '@swc/*'
  - 'heading-case'

patchedDependencies:
  webpack-sources@3.3.4: patches/webpack-sources@3.3.4.patch

# Prevent un-reviewed build scripts
strictDepBuilds: true
