[toolchain]
profile = "default"
# Use nightly for better access to the latest Rust features.
# This date is aligned to stable release dates.
# stable-2025-03-18 -> v1.85.1
channel = "nightly-2025-03-18"
