it("css modules localIdentName with hash", () => {
	const style = require("./index.css");
	expect(style).toEqual({
		"#": "jm1Lo11ecZW",
		"##": "UFT78j3VmLq",
		"#.#.#": "az-prjsEqMO",
		"#fake-id": "TYdq-OjT1aa",
		"++++++++++[>+++++++>++++++++++>+++>+<<<<-]>++.>+.+++++++..+++.>++.<<+++++++++++++++.>.+++.------.--------.>+.>.":
			"Olcq75WQMgu",
		"-a-b-c-": "h0IT5oNe-bO",
		"-a0-34a___f": "XDZ-8fQSVRW",
		".": "Y5qL8fGSOl5",
		123: "cXoAKR43PcO",
		"1a2b3c": "ZVdBkSapBBS",
		":)": "-nLVnVpoPZm",
		":`(": "QePBQVTaEYG",
		":hover": "_1TwUF-KyPLK",
		":hover:focus:active": "u6tplhurC3O",
		"<><<<>><>": "GwYNBfhWWWW",
		"<p>": "fz9GoC_48Zi",
		"?": "cv9mIZ2iyQ1",
		"@": "ckxl52cCPO5",
		"B&W?": "gGoyPHkLUMe",
		"[attr=value]": "iwSghNxKq55",
		_: "ktZ96kc0VhG",
		_test: "QmszZ4y1rsS",
		className: "r4rzFVQp3iG",
		"f!o!o": "Kte7eWlkRla",
		"f'o'o": "UpjbMSWS7SO",
		"f*o*o": "Yzr8ELpDxCS",
		"f+o+o": "iMl9J4GP9ie",
		"f/o/o": "UImPgS-j-BG",
		"f\\o\\o": "XVH9eAUI47G",
		"foo.bar": "_5p5LShiOYgC",
		"foo/bar": "EiY-akobl0G",
		"foo/bar/baz": "vyBBm_JnUHi",
		"foo\\bar": "_4Adk1K_G1tK",
		"foo\\bar\\baz": "-C1sHlzpYlC",
		"f~o~o": "UmF4wWCJbwa",
		"m_x_@": "-mV09Raz-Wq",
		someId: "nx6FwQoSnji",
		subClass: "Pdw4Xh6_KNm",
		test: "V30RvNuRIS1",
		"{}": "rg6c2gRopNW",
		"©": "Gy34V_uKLPu",
		"“‘’”": "tENVqSUEyPK",
		"⌘⌥": "_fjIAUPhHBm",
		"☺☃": "GCvAg3nvOxW",
		"♥": "m-GqSIqxXQO",
		"𝄞♪♩♫♬": "fDvgz1V1fMa",
		"💩": "OnGeHeRRl69",
		"😍": "u9lv3RA5KiO"
	});
});
