const path = require("node:path");
const { readFileSync, writeFileSync, renameSync, appendFileSync } = require("node:fs");
const { values, positionals } = require("node:util").parseArgs({
	args: process.argv.slice(2),
	options: {
		profile: {
			type: "string"
		},
	},
	strict: true,
	allowPositionals: true
});

const { spawn, spawnSync } = require("node:child_process");

const NAPI_BINDING_DTS = "napi-binding.d.ts"
const CARGO_SAFELY_EXIT_CODE = 0;

const watch = process.argv.includes("--watch");

const measureFresh = process.env.MEASURE_CARGO_FRESH === "1" && !watch;

build().then((value) => {
	// Regarding cargo's non-zero exit code as an error.
	if (value !== CARGO_SAFELY_EXIT_CODE) {
		process.exit(value);
	}
}).catch(err => {
	console.error(err);
	process.exit(1);
});

async function build() {
	return new Promise((resolve, reject) => {
		const args = [
			"build",
			"--platform",
			"--dts",
			NAPI_BINDING_DTS,
			"--no-js",
			// "--no-const-enum",
			"--no-dts-header",
			"--pipe",
			`"node ${path.resolve(__dirname, "dts-header.js")}"`
		];
		const rustflags = []
		const features = [];
		const envs = { ...process.env };
		const use_build_std = values.profile === "release"
			|| values.profile === "release-debug"
			|| values.profile === "release-wasi"
			|| values.profile === "profiling";

		if (values.profile) {
			args.push("--profile", values.profile);
		}
		if (watch) {
			args.push("--watch");
		}
		if (process.env.USE_NAPI_CROSS) {
			args.push("--use-napi-cross");
		}
		if (process.env.USE_ZIG) {
			args.push("--cross-compile");
		}
		if (process.env.RUST_TARGET) {
			args.push("--target", process.env.RUST_TARGET);
		}
		if (!process.env.DISABLE_PLUGIN) {
			args.push("--no-default-features");
			features.push("plugin");
		}
		if (process.env.RSPACK_TARGET_BROWSER) {
			features.push("browser")
		}
		if (values.profile !== "release") {
			features.push("perfetto");
		}
		args.push("--no-dts-cache");
		if (process.env.SFTRACE) {
			features.push("sftrace-setup");
			rustflags.push("-Zinstrument-xray=always");
		}
		if (process.env.ALLOCATIVE) {
			features.push("allocative");
			rustflags.push("--cfg=allocative");
		}
		if (process.env.TRACY) {
			features.push("tracy-client");
		}
		if (values.profile === "release") {
			features.push("info-level");
			rustflags.push("-Zlocation-detail=none");
			if (process.env.RUST_TARGET && !process.env.RUST_TARGET.includes("windows-msvc")) {
				rustflags.push("-Cforce-unwind-tables=no");
			}
		} else {
			// enable unwind-table for backtrace for non-release profile
			if (!process.env.RUST_TARGET || (process.env.RUST_TARGET && !process.env.RUST_TARGET.includes("windows-msvc"))) {
				rustflags.push("-Cforce-unwind-tables=yes");
			}

		}
		if (features.length) {
			args.push(`--features ${features.join(",")}`);
		}

		if (positionals.length > 0 || rustflags.length > 0 || use_build_std || measureFresh) {
			// napi need `--` to separate options and positional arguments.
			args.push("--");

			if (rustflags.length > 0) {
				const flag = rustflags.map(f => `\\"${f}\\"`).join(",");
				args.push("--config");
				args.push(`"target.'cfg(all())'.rustflags = [${flag}]"`)
			}

			if (use_build_std) {
				// allows to optimize std with current compile arguments
				// and avoids std code generate unwind table to save size.
				args.push("-Zbuild-std=panic_abort,std");
			}

			if (measureFresh) {
				args.push("--message-format=json-render-diagnostics");
			}

			if (positionals.length > 0) {
				args.push(...positionals);
			}
		}

		console.log(`Run command: napi ${args.join(" ")}`);

		const cp = spawn("napi", args, {
			stdio: measureFresh ? ["inherit", "pipe", "inherit"] : "inherit",
			shell: true,
			env: envs,
		});

		const freshStats = measureFresh ? collectFreshStats(cp.stdout) : null;

		cp.on("error", reject);
		cp.on("close", (code) => {
			if (code === CARGO_SAFELY_EXIT_CODE) {
				// Fix an issue where napi cli does not generate `string_enum` with `enum`s.
				const dts = path.resolve(__dirname, "..", NAPI_BINDING_DTS);
				writeFileSync(dts,
					readFileSync(dts, "utf8")
						.replaceAll("const enum", "enum")
						// Remove the NormalModule type declaration generated by N-API.
						// We manually declare the NormalModule type in banner.d.ts
						// This allows users to extend NormalModule with static methods through type augmentation.
						.replaceAll(/export\s+declare\s+class\s+NormalModule\s*\{([\s\S]*?)\}\s*(?=\n\s*(?:export|declare|class|$))/g, "")
				);

				// For browser wasm, we rename the artifacts to distinguish them from node wasm
				if (process.env.RSPACK_TARGET_BROWSER) {
					renameSync("rspack.wasm32-wasi.debug.wasm", "rspack.browser.debug.wasm")
					renameSync("rspack.wasm32-wasi.wasm", "rspack.browser.wasm")
				}

				if (process.env.TRACY) {
					// split debug symbols for tracy
					spawnSync('dsymutil', [
						path.resolve(__dirname, "..", "rspack.darwin-arm64.node")
					], {
						stdio: "inherit",
						shell: true,
					})
				}

				if (freshStats) {
					reportFreshStats(freshStats);
				}
			}
			resolve(code);
		});
	});
}

function collectFreshStats(stdout) {
	const stats = { fresh: 0, total: 0, notFresh: [] };
	stdout.setEncoding("utf8");
	let buffer = "";
	stdout.on("data", chunk => {
		buffer += chunk;
		let nl;
		while ((nl = buffer.indexOf("\n")) !== -1) {
			const line = buffer.slice(0, nl).replace(/\r$/, "");
			buffer = buffer.slice(nl + 1);
			let msg;
			try {
				msg = JSON.parse(line);
			} catch {
				process.stdout.write(line + "\n");
				continue;
			}
			if (msg.reason === "compiler-artifact" && typeof msg.fresh === "boolean") {
				stats.total += 1;
				if (msg.fresh) stats.fresh += 1;
				else if (msg.target && msg.target.name) stats.notFresh.push(msg.target.name);
			}
		}
	});
	return stats;
}

function reportFreshStats({ fresh, total, notFresh = [] }) {
	const target = process.env.RUST_TARGET || "host";
	const pct = total ? ((fresh / total) * 100).toFixed(1) : "0.0";
	const summary = `${target}: ${fresh}/${total} units fresh = ${pct}% rust cache utilization`;
	const escapedSummary = summary.replace(/%/g, "%25").replace(/\r/g, "%0D").replace(/\n/g, "%0A");
	console.log(`\n::notice title=Rust Cache Utilization::${escapedSummary}`);
	const recompiled = [...new Set(notFresh)].sort();
	console.log(`::notice title=Recompiled Units::${target}: ${recompiled.join(", ")}`);
	if (process.env.GITHUB_STEP_SUMMARY) {
		appendFileSync(
			process.env.GITHUB_STEP_SUMMARY,
			`### Rust cache utilization — \`${target}\`\n\n` +
				`| fresh | recompiled | total | utilization |\n` +
				`| ----: | ---------: | ----: | ----------: |\n` +
				`| ${fresh} | ${total - fresh} | ${total} | **${pct}%** |\n\n` +
				`<details><summary>${recompiled.length} recompiled units</summary>\n\n${recompiled.join(", ")}\n\n</details>\n\n`
		);
	}
}
