export * from "path";
import data from "./data.json";
import generatedDefault from "./generated-default";

const __rspack_reexport = "user reexport";
const __rspack_import_key = "user import key";
const __rspack_default_export = "user default export";

export { __rspack_reexport, __rspack_import_key, __rspack_default_export };

it("should deconflict identifiers generated by dependency templates", async () => {
	const output = await import(/* webpackIgnore: true */ "./main.mjs");
	const path = await import("path");

	expect(output.sep).toBe(path.sep);
	expect(output.__rspack_reexport).toBe("user reexport");
	expect(output.__rspack_import_key).toBe("user import key");
	expect(output.__rspack_default_export).toBe("user default export");
	expect(generatedDefault).toBe(42);
	expect(data.value).toBe("__rspack_symbol_0__\0");
});
