[package]
authors     = ["Rspack Teams"]
description = "Rspack Dylint rules for high-performance map/set hashers"
edition     = "2021"
name        = "rspack_collection_hasher"
publish     = false
version     = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
clippy_utils   = { git = "https://github.com/rust-lang/rust-clippy", rev = "a55b8533bef24d86e43ac873c8b26573b9864864" }
dylint_linting = "6.0.4"

[dev-dependencies]
dashmap            = "6.1.0"
dylint_testing     = "6.0.4"
hashlink           = "0.10.0"
indexmap           = "2.13.0"
rspack_collections = { path = "../../crates/rspack_collections" }
rustc-hash         = "2.1.1"
ustr               = { package = "ustr-fxhash", version = "1.0.1", default-features = false }

[workspace]

[package.metadata.rust-analyzer]
rustc_private = true
