import { value } from './file';

const fs = require('fs');
const path = require('path');

it("should not change content of html file which generated by html-rspack-plugin", async () => {
	expect(value).toBe(0);
	const original = fs.readFileSync(path.resolve(__dirname, './index.html'), 'utf-8');
	await NEXT_HMR();
	expect(value).toBe(1);
	const updated = fs.readFileSync(path.resolve(__dirname, './index.html'), 'utf-8');
	expect(original).toEqual(updated);
});

module.hot.accept("./file");
