/* auto-generated by NAPI-RS */
/* eslint-disable */

/* -- banner.d.ts -- */
export type JsFilename =
	| string
	| ((pathData: JsPathData, assetInfo?: AssetInfo) => string);

export type RawLazyCompilationTest = RegExp | ((module: Module) => boolean);

export type AssetInfo = KnownAssetInfo & Record<string, any>;

export type CustomPluginName = string;

export const MODULE_IDENTIFIER_SYMBOL: unique symbol;

export const COMPILATION_HOOKS_MAP_SYMBOL: unique symbol;

export const BUILD_INFO_ASSETS_SYMBOL: unique symbol;
export const BUILD_INFO_FILE_DEPENDENCIES_SYMBOL: unique symbol;
export const BUILD_INFO_CONTEXT_DEPENDENCIES_SYMBOL: unique symbol;
export const BUILD_INFO_MISSING_DEPENDENCIES_SYMBOL: unique symbol;
export const BUILD_INFO_BUILD_DEPENDENCIES_SYMBOL: unique symbol;
export const COMMIT_CUSTOM_FIELDS_SYMBOL: unique symbol;

export const RUST_ERROR_SYMBOL: unique symbol;

interface KnownBuildInfo {
	[BUILD_INFO_ASSETS_SYMBOL]: Assets,
	[BUILD_INFO_FILE_DEPENDENCIES_SYMBOL]: string[],
	[BUILD_INFO_CONTEXT_DEPENDENCIES_SYMBOL]: string[],
	[BUILD_INFO_MISSING_DEPENDENCIES_SYMBOL]: string[],
	[BUILD_INFO_BUILD_DEPENDENCIES_SYMBOL]: string[],
	[COMMIT_CUSTOM_FIELDS_SYMBOL](): void;
}

export type BuildInfo = KnownBuildInfo & Record<string, any>;

export interface Module {
	[MODULE_IDENTIFIER_SYMBOL]: string;
	readonly type: string;
	get context(): string | undefined;
	get layer(): string | undefined;
	get factoryMeta(): JsFactoryMeta
	set factoryMeta(factoryMeta: JsFactoryMeta);
	get useSourceMap(): boolean;
	get useSimpleSourceMap(): boolean;
	buildInfo: BuildInfo;
	buildMeta: Record<string, any>;
}

interface NormalModuleConstructor {
	new(): NormalModule;
	readonly prototype: NormalModule;
}

export var NormalModule: NormalModuleConstructor;

export interface NormalModule extends Module {
	readonly resource: string;
	readonly request: string;
	readonly userRequest: string;
	readonly rawRequest: string;
	readonly resourceResolveData: Readonly<JsResourceData> | undefined;
	readonly loaders: JsLoaderItem[];
	get matchResource(): string | undefined;
	set matchResource(val: string | undefined);
}

export interface ConcatenatedModule extends Module {
}

export interface ContextModule extends Module {
}

export interface ExternalModule extends Module {
	readonly userRequest: string;
}

export interface RspackError extends Error {
	name: string;
	message: string;
	details?: string;
	module?: null | Module;
	loc?: DependencyLocation;
	file?: string;
	stack?: string;
	hideStack?: boolean;
	error?: Error;
}

export type DependencyLocation = SyntheticDependencyLocation | RealDependencyLocation;
/* -- banner.d.ts end -- */

/* -- napi-rs generated below -- */

export declare class ExternalObject<T> {
	readonly '': {
		readonly '': unique symbol
		[K: symbol]: T
	}
}
export declare class Assets {
	keys(): Array<string>
}

export declare class AsyncDependenciesBlock {
	get dependencies(): Dependency[]
	get blocks(): AsyncDependenciesBlock[]
}

export declare class Chunk {
	get name(): string | undefined
	get id(): string | undefined
	get ids(): Array<string>
	get idNameHints(): Array<string>
	get filenameTemplate(): string | undefined
	get cssFilenameTemplate(): string | undefined
	get _files(): Array<string>
	get _runtime(): Array<string>
	get hash(): string | undefined
	get contentHash(): Record<string, string>
	get renderedHash(): string | undefined
	get chunkReason(): string | undefined
	get _auxiliaryFiles(): Array<string>
	isOnlyInitial(): boolean
	canBeInitial(): boolean
	hasRuntime(): boolean
	getAllAsyncChunks(): Chunk[]
	getAllInitialChunks(): Chunk[]
	getAllReferencedChunks(): Chunk[]
	get _groupsIterable(): ChunkGroup[]
	getEntryOptions(): EntryOptionsDTO | undefined
}

export declare class ChunkGraph {
	hasChunkEntryDependentChunks(chunk: Chunk): boolean
	getChunkModules(chunk: Chunk): Module[]
	getChunkModulesIterable(chunk: Chunk): Iterable<Module>
	getChunkEntryModulesIterable(chunk: Chunk): Iterable<Module>
	getNumberOfEntryModules(chunk: Chunk): number
	getChunkEntryDependentChunksIterable(chunk: Chunk): Chunk[]
	getChunkModulesIterableBySourceType(chunk: Chunk, sourceType: string): Module[]
	getModuleChunks(module: Module): Chunk[]
	getModuleId(module: Module): string | number | null
	_getModuleHash(module: Module, runtime: string | string[] | undefined): string | null
	getBlockChunkGroup(jsBlock: AsyncDependenciesBlock): ChunkGroup | null
}

export declare class ChunkGroup {
	get chunks(): Chunk[]
	get index(): number | undefined
	get name(): string | undefined
	get origins(): Array<JsChunkGroupOrigin>
	get childrenIterable(): ChunkGroup[]
	isInitial(): boolean
	getParents(): ChunkGroup[]
	getRuntimeChunk(): Chunk
	getEntrypointChunk(): Chunk
	getFiles(): Array<string>
	getModulePreOrderIndex(module: Module): number | null
	getModulePostOrderIndex(module: Module): number | null
}

export declare class Chunks {
	get size(): number
	_values(): Chunk[]
	_has(chunk: Chunk): boolean
}

export declare class CodeGenerationResult {
	get sources(): Sources
}

export declare class CodeGenerationResults {
	get(module: Module, runtime: string | string[] | undefined): CodeGenerationResult
}

export declare class ConcatenatedModule {
	get rootModule(): Module
	get modules(): Module[]
	readableIdentifier(): string
	_originalSource(): JsCompatSource | undefined
	nameForCondition(): string | undefined
	get blocks(): AsyncDependenciesBlock[]
	get dependencies(): Dependency[]
	size(ty?: string | undefined | null): number
	libIdent(options: JsLibIdentOptions): string | null
	_emitFile(filename: string, source: JsCompatSource, assetInfo?: AssetInfo | undefined | null): void
}

export declare class ContextModule {
	readableIdentifier(): string
	_originalSource(): JsCompatSource | undefined
	nameForCondition(): string | undefined
	get blocks(): AsyncDependenciesBlock[]
	get dependencies(): Dependency[]
	size(ty?: string | undefined | null): number
	libIdent(options: JsLibIdentOptions): string | null
	_emitFile(filename: string, source: JsCompatSource, assetInfo?: AssetInfo | undefined | null): void
}

export declare class Dependency {
	get _parentModule(): Module | undefined
	get type(): string
	get category(): string
	get request(): string | undefined
	get critical(): boolean
	set critical(val: boolean)
	get ids(): Array<string> | undefined
}

export declare class Diagnostics {
	get length(): number
	values(): Array<RspackError>
	get(index: number): RspackError | undefined
	set(index: number, error: RspackError): void
	spliceWithArray(index: number, deleteCount?: number | undefined | null, newItems?: Array<RspackError> | undefined | null): Array<RspackError>
}

export declare class EntryDataDto {
	get dependencies(): Dependency[]
	get includeDependencies(): Dependency[]
	get options(): EntryOptionsDto
}
export type EntryDataDTO = EntryDataDto

export declare class EntryDependency {
	constructor(request: string)
	get type(): string
	get category(): string
	get request(): string | undefined
}

export declare class EntryOptionsDto {
	get name(): string | undefined
	set name(name: string | undefined)
	get runtime(): false | string | undefined
	set runtime(chunkLoading: boolean | string | undefined)
	get chunkLoading(): string | undefined
	set chunkLoading(chunkLoading: string | false | undefined)
	get asyncChunks(): boolean | undefined
	set asyncChunks(asyncChunks: boolean | undefined)
	get baseUri(): string | undefined
	set baseUri(baseUri: string | undefined)
	get library(): JsLibraryOptions | undefined
	set library(library: JsLibraryOptions | undefined)
	get dependOn(): Array<string> | undefined
	set dependOn(dependOn: Array<string> | undefined)
	get layer(): string | undefined
	set layer(layer: string | undefined)
}
export type EntryOptionsDTO = EntryOptionsDto

export declare class ExternalModule {
	readableIdentifier(): string
	_originalSource(): JsCompatSource | undefined
	nameForCondition(): string | undefined
	get blocks(): AsyncDependenciesBlock[]
	get dependencies(): Dependency[]
	size(ty?: string | undefined | null): number
	libIdent(options: JsLibIdentOptions): string | null
	_emitFile(filename: string, source: JsCompatSource, assetInfo?: AssetInfo | undefined | null): void
}

export declare class JsCompilation {
	updateAsset(filename: string, newSourceOrFunction: JsCompatSource | ((source: JsCompatSourceOwned) => JsCompatSourceOwned), assetInfoUpdateOrFunction?: AssetInfo | ((assetInfo: AssetInfo) => AssetInfo | undefined)): void
	getAssets(): Readonly<JsAsset>[]
	getAsset(name: string): JsAsset | null
	getAssetSource(name: string): JsCompatSource | null
	get modules(): Array<Module>
	get builtModules(): Array<Module>
	getOptimizationBailout(): Array<JsStatsOptimizationBailout>
	get chunks(): Chunks
	getNamedChunkKeys(): Array<string>
	getNamedChunk(name: string): Chunk
	getNamedChunkGroupKeys(): Array<string>
	getNamedChunkGroup(name: string): ChunkGroup
	setAssetSource(name: string, source: JsCompatSource): void
	deleteAssetSource(name: string): void
	getAssetFilenames(): Array<string>
	hasAsset(name: string): boolean
	emitAsset(filename: string, source: JsCompatSource, assetInfo?: AssetInfo | undefined | null): void
	deleteAsset(filename: string): void
	renameAsset(filename: string, newName: string): void
	get entrypoints(): ChunkGroup[]
	get chunkGroups(): ChunkGroup[]
	get hash(): string | null
	dependencies(): JsDependencies
	pushDiagnostic(diagnostic: JsRspackDiagnostic): void
	pushNativeDiagnostic(diagnostic: ExternalObject<'Diagnostic'>): void
	pushNativeDiagnostics(diagnostics: ExternalObject<'Diagnostic[]'>): void
	get errors(): Diagnostics
	get warnings(): Diagnostics
	getErrors(): Array<RspackError>
	getWarnings(): Array<RspackError>
	getStats(): JsStats
	getAssetPath(filename: string, data: JsPathData): string
	getAssetPathWithInfo(filename: string, data: JsPathData): PathWithInfo
	getPath(filename: string, data: JsPathData): string
	getPathWithInfo(filename: string, data: JsPathData): PathWithInfo
	addFileDependencies(deps: Array<string>): void
	addContextDependencies(deps: Array<string>): void
	addMissingDependencies(deps: Array<string>): void
	addBuildDependencies(deps: Array<string>): void
	/**
	 * This is a very unsafe function.
	 * Please don't use this at the moment.
	 * Using async and mutable reference to `Compilation` at the same time would likely to cause data races.
	 */
	rebuildModule(moduleIdentifiers: Array<string>, f: any): void
	importModule(request: string, layer: string | undefined | null, publicPath: JsFilename | undefined | null, baseUri: string | undefined | null, originalModule: string, originalModuleContext: string | undefined | null, callback: any): void
	get entries(): JsEntries
	addRuntimeModule(chunk: Chunk, runtimeModule: JsAddingRuntimeModule): void
	get moduleGraph(): JsModuleGraph
	get chunkGraph(): ChunkGraph
	addEntry(args: [string, EntryDependency, JsEntryOptions | undefined][], callback: (errMsg: Error | null, results: [string | null, Module][]) => void): void
	addInclude(args: [string, EntryDependency, JsEntryOptions | undefined][], callback: (errMsg: Error | null, results: [string | null, Module][]) => void): void
	get codeGenerationResults(): CodeGenerationResults
	createStatsWarnings(warnings: Array<RspackError>, colored?: boolean | undefined | null): JsStatsError[]
}

export declare class JsCompiler {
	constructor(compilerPath: string, options: RawOptions, builtinPlugins: Array<BuiltinPlugin>, registerJsTaps: RegisterJsTaps, outputFilesystem: ThreadsafeNodeFS, intermediateFilesystem: ThreadsafeNodeFS | undefined | null, inputFilesystem: ThreadsafeNodeFS | undefined | null, resolverFactoryReference: JsResolverFactory)
	setNonSkippableRegisters(kinds: Array<RegisterJsTapKind>): void
	/** Build with the given option passed to the constructor */
	build(callback: (err: null | Error) => void): void
	/** Rebuild with the given option passed to the constructor */
	rebuild(changed_files: string[], removed_files: string[], callback: (err: null | Error) => void): void
	close(): Promise<void>
}

export declare class JsContextModuleFactoryAfterResolveData {
	get resource(): string
	set resource(resource: string)
	get context(): string
	set context(context: string)
	get request(): string
	set request(request: string)
	get regExp(): RegExp | undefined
	set regExp(rawRegExp: RegExp | undefined)
	get recursive(): boolean
	set recursive(recursive: boolean)
	get dependencies(): Dependency[]
}

export declare class JsContextModuleFactoryBeforeResolveData {
	get context(): string
	set context(context: string)
	get request(): string
	set request(request: string)
	get regExp(): RegExp | undefined
	set regExp(rawRegExp: RegExp | undefined)
	get recursive(): boolean
	set recursive(recursive: boolean)
}

export declare class JsDependencies {
	get fileDependencies(): Array<string>
	get addedFileDependencies(): Array<string>
	get removedFileDependencies(): Array<string>
	get contextDependencies(): Array<string>
	get addedContextDependencies(): Array<string>
	get removedContextDependencies(): Array<string>
	get missingDependencies(): Array<string>
	get addedMissingDependencies(): Array<string>
	get removedMissingDependencies(): Array<string>
	get buildDependencies(): Array<string>
	get addedBuildDependencies(): Array<string>
	get removedBuildDependencies(): Array<string>
}

export declare class JsEntries {
	clear(): void
	get size(): number
	has(key: string): boolean
	set(key: string, value: JsEntryData | EntryDataDto): void
	delete(key: string): boolean
	get(key: string): EntryDataDto | undefined
	keys(): Array<string>
	values(): Array<EntryDataDto>
}

export declare class JsExportsInfo {
	isUsed(runtime: string | string[] | undefined): boolean
	isModuleUsed(runtime: string | string[] | undefined): boolean
	setUsedInUnknownWay(runtime: string | string[] | undefined): boolean
	getUsed(name: string | string[], runtime: string | string[] | undefined): 0 | 1 | 2 | 3 | 4
}

export declare class JsModuleGraph {
	getModule(dependency: Dependency): Module | null
	getResolvedModule(dependency: Dependency): Module | null
	getUsedExports(module: Module, runtime: string | string[]): boolean | Array<string> | null
	getIssuer(module: Module): Module | null
	getExportsInfo(module: Module): JsExportsInfo
	getConnection(dependency: Dependency): ModuleGraphConnection | null
	getOutgoingConnections(module: Module): ModuleGraphConnection[]
	getOutgoingConnectionsInOrder(module: Module): ModuleGraphConnection[]
	getIncomingConnections(module: Module): ModuleGraphConnection[]
	getParentModule(dependency: Dependency): Module | null
	getParentBlockIndex(dependency: Dependency): number
	isAsync(module: Module): boolean
}

export declare class JsResolver {
	resolveSync(path: string, request: string): JsResourceData | false
	resolve(path: string, request: string, callback: (err: null | Error, req?: JsResourceData) => void): void
	withOptions(raw?: RawResolveOptionsWithDependencyType | undefined | null): JsResolver
}

export declare class JsResolverFactory {
	constructor(pnp: boolean)
	get(type: string, options?: RawResolveOptionsWithDependencyType): JsResolver
}

export declare class JsStats {
	toJson(jsOptions: JsStatsOptions): JsStatsCompilation
	getLogging(acceptedTypes: number): Array<JsStatsLogging>
}

export declare class KnownBuildInfo {

}

export declare class Module {
	readableIdentifier(): string
	_originalSource(): JsCompatSource | undefined
	nameForCondition(): string | undefined
	get blocks(): AsyncDependenciesBlock[]
	get dependencies(): Dependency[]
	size(ty?: string | undefined | null): number
	libIdent(options: JsLibIdentOptions): string | null
	_emitFile(filename: string, source: JsCompatSource, assetInfo?: AssetInfo | undefined | null): void
}

export declare class ModuleGraphConnection {
	get dependency(): Dependency
	get module(): Module | null
	get resolvedModule(): Module | null
	get originModule(): Module | null
}

export declare class NativeWatcher {
	constructor(options: NativeWatcherOptions)
	watch(files: [Array<string>, Array<string>], directories: [Array<string>, Array<string>], missing: [Array<string>, Array<string>], callback: (err: Error | null, result: NativeWatchResult) => void, callbackUndelayed: (path: string) => void): void
	/**
	 * # Safety
	 *
	 * This function is unsafe because it uses `&mut self` to call the watcher asynchronously.
	 * It's important to ensure that the watcher is not used in any other places before this function is finished.
	 * You must ensure that the watcher not call watch, close or pause in the same time, otherwise it may lead to undefined behavior.
	 */
	close(): Promise<void>
	pause(): void
}

export declare class NativeWatchResult {
	changedFiles: Array<string>
	removedFiles: Array<string>
}


export declare class RawExternalItemFnCtx {
	data(): RawExternalItemFnCtxData
	getResolver(): JsResolver
}

export declare class ReadonlyResourceData {
	get descriptionFileData(): any
	get descriptionFilePath(): string
}

export declare class Sources {
	_get(sourceType: string): JsCompatSourceOwned | null
}

export interface BuiltinPlugin {
	name: BuiltinPluginName | CustomPluginName
	options: unknown
	canInherentFromParent?: boolean
}

export declare enum BuiltinPluginName {
	DefinePlugin = 'DefinePlugin',
	ProvidePlugin = 'ProvidePlugin',
	BannerPlugin = 'BannerPlugin',
	IgnorePlugin = 'IgnorePlugin',
	ProgressPlugin = 'ProgressPlugin',
	EntryPlugin = 'EntryPlugin',
	DynamicEntryPlugin = 'DynamicEntryPlugin',
	ExternalsPlugin = 'ExternalsPlugin',
	NodeTargetPlugin = 'NodeTargetPlugin',
	ElectronTargetPlugin = 'ElectronTargetPlugin',
	EnableChunkLoadingPlugin = 'EnableChunkLoadingPlugin',
	EnableLibraryPlugin = 'EnableLibraryPlugin',
	EnableWasmLoadingPlugin = 'EnableWasmLoadingPlugin',
	FetchCompileAsyncWasmPlugin = 'FetchCompileAsyncWasmPlugin',
	ChunkPrefetchPreloadPlugin = 'ChunkPrefetchPreloadPlugin',
	CommonJsChunkFormatPlugin = 'CommonJsChunkFormatPlugin',
	ArrayPushCallbackChunkFormatPlugin = 'ArrayPushCallbackChunkFormatPlugin',
	ModuleChunkFormatPlugin = 'ModuleChunkFormatPlugin',
	EsmLibraryPlugin = 'EsmLibraryPlugin',
	HotModuleReplacementPlugin = 'HotModuleReplacementPlugin',
	LimitChunkCountPlugin = 'LimitChunkCountPlugin',
	WorkerPlugin = 'WorkerPlugin',
	WebWorkerTemplatePlugin = 'WebWorkerTemplatePlugin',
	MergeDuplicateChunksPlugin = 'MergeDuplicateChunksPlugin',
	SplitChunksPlugin = 'SplitChunksPlugin',
	RemoveDuplicateModulesPlugin = 'RemoveDuplicateModulesPlugin',
	ShareRuntimePlugin = 'ShareRuntimePlugin',
	ContainerPlugin = 'ContainerPlugin',
	ContainerReferencePlugin = 'ContainerReferencePlugin',
	ProvideSharedPlugin = 'ProvideSharedPlugin',
	ConsumeSharedPlugin = 'ConsumeSharedPlugin',
	ModuleFederationRuntimePlugin = 'ModuleFederationRuntimePlugin',
	NamedModuleIdsPlugin = 'NamedModuleIdsPlugin',
	NaturalModuleIdsPlugin = 'NaturalModuleIdsPlugin',
	DeterministicModuleIdsPlugin = 'DeterministicModuleIdsPlugin',
	NaturalChunkIdsPlugin = 'NaturalChunkIdsPlugin',
	NamedChunkIdsPlugin = 'NamedChunkIdsPlugin',
	DeterministicChunkIdsPlugin = 'DeterministicChunkIdsPlugin',
	OccurrenceChunkIdsPlugin = 'OccurrenceChunkIdsPlugin',
	RealContentHashPlugin = 'RealContentHashPlugin',
	RemoveEmptyChunksPlugin = 'RemoveEmptyChunksPlugin',
	EnsureChunkConditionsPlugin = 'EnsureChunkConditionsPlugin',
	WarnCaseSensitiveModulesPlugin = 'WarnCaseSensitiveModulesPlugin',
	DataUriPlugin = 'DataUriPlugin',
	FileUriPlugin = 'FileUriPlugin',
	RuntimePlugin = 'RuntimePlugin',
	JsonModulesPlugin = 'JsonModulesPlugin',
	InferAsyncModulesPlugin = 'InferAsyncModulesPlugin',
	JavascriptModulesPlugin = 'JavascriptModulesPlugin',
	AsyncWebAssemblyModulesPlugin = 'AsyncWebAssemblyModulesPlugin',
	AssetModulesPlugin = 'AssetModulesPlugin',
	SourceMapDevToolPlugin = 'SourceMapDevToolPlugin',
	EvalSourceMapDevToolPlugin = 'EvalSourceMapDevToolPlugin',
	EvalDevToolModulePlugin = 'EvalDevToolModulePlugin',
	SideEffectsFlagPlugin = 'SideEffectsFlagPlugin',
	FlagDependencyExportsPlugin = 'FlagDependencyExportsPlugin',
	FlagDependencyUsagePlugin = 'FlagDependencyUsagePlugin',
	MangleExportsPlugin = 'MangleExportsPlugin',
	ModuleConcatenationPlugin = 'ModuleConcatenationPlugin',
	CssModulesPlugin = 'CssModulesPlugin',
	APIPlugin = 'APIPlugin',
	RuntimeChunkPlugin = 'RuntimeChunkPlugin',
	SizeLimitsPlugin = 'SizeLimitsPlugin',
	NoEmitOnErrorsPlugin = 'NoEmitOnErrorsPlugin',
	ContextReplacementPlugin = 'ContextReplacementPlugin',
	DllEntryPlugin = 'DllEntryPlugin',
	DllReferenceAgencyPlugin = 'DllReferenceAgencyPlugin',
	LibManifestPlugin = 'LibManifestPlugin',
	FlagAllModulesAsUsedPlugin = 'FlagAllModulesAsUsedPlugin',
	HttpExternalsRspackPlugin = 'HttpExternalsRspackPlugin',
	CopyRspackPlugin = 'CopyRspackPlugin',
	HtmlRspackPlugin = 'HtmlRspackPlugin',
	SwcJsMinimizerRspackPlugin = 'SwcJsMinimizerRspackPlugin',
	LightningCssMinimizerRspackPlugin = 'LightningCssMinimizerRspackPlugin',
	BundlerInfoRspackPlugin = 'BundlerInfoRspackPlugin',
	CssExtractRspackPlugin = 'CssExtractRspackPlugin',
	SubresourceIntegrityPlugin = 'SubresourceIntegrityPlugin',
	RsdoctorPlugin = 'RsdoctorPlugin',
	RstestPlugin = 'RstestPlugin',
	RslibPlugin = 'RslibPlugin',
	CircularDependencyRspackPlugin = 'CircularDependencyRspackPlugin',
	JsLoaderRspackPlugin = 'JsLoaderRspackPlugin',
	LazyCompilationPlugin = 'LazyCompilationPlugin',
	ModuleInfoHeaderPlugin = 'ModuleInfoHeaderPlugin',
	HttpUriPlugin = 'HttpUriPlugin',
	CssChunkingPlugin = 'CssChunkingPlugin'
}

export declare function cleanupGlobalTrace(): void

export interface ContextInfo {
	issuer: string
	issuerLayer?: string
}

export interface CssChunkingPluginOptions {
	strict?: boolean
	minSize?: number
	maxSize?: number
	exclude?: RegExp
}

/**
 * We manually create binding.d.ts and re-export everything of the dts generated by napi to fix the cjs-esm interop
 */

import * as binding from "./napi-binding";

export * from "./napi-binding"
export default binding;
