/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export interface RawOptions {
  entries: Array<string>
  minify: boolean
  outdir?: string
  entryFileNames: string
  loader?: Record<string, string>
  inlineStyle?: boolean
  alias?: Record<string, string>
  refresh?: boolean
}
export interface RspackInternal {
  
}
export function newRspack(optionJson: string): ExternalObject<RspackInternal>
export function build(rspack: ExternalObject<RspackInternal>): object
export function rebuild(rspack: ExternalObject<RspackInternal>, changed_file: string): object
export interface ResolveRet {
  status: boolean
  result?: string
}
export function resolve(rspack: ExternalObject<RspackInternal>, id: string, dir: string): object
