/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const __nodeFs = require('node:fs')
const __nodePath = require('node:path')
const { WASI: __nodeWASI } = require('node:wasi')
const { Worker } = require('node:worker_threads')

const {
  createOnMessage: __wasmCreateOnMessageForFsProxy,
  getDefaultContext: __emnapiGetDefaultContext,
  instantiateNapiModuleSync: __emnapiInstantiateNapiModuleSync,
} = require('@napi-rs/wasm-runtime')

const __rootDir = __nodePath.parse(process.cwd()).root

const __wasi = new __nodeWASI({
  version: 'preview1',
  env: process.env,
  preopens: {
    [__rootDir]: __rootDir,
  }
})

const __emnapiContext = __emnapiGetDefaultContext()

const __sharedMemory = new WebAssembly.Memory({
  initial: 16384,
  maximum: 65536,
  shared: true,
})

let __wasmFilePath = __nodePath.join(__dirname, 'rspack.wasm32-wasi.wasm')
const __wasmDebugFilePath = __nodePath.join(__dirname, 'rspack.wasm32-wasi.debug.wasm')

if (__nodeFs.existsSync(__wasmDebugFilePath)) {
  __wasmFilePath = __wasmDebugFilePath
} else if (!__nodeFs.existsSync(__wasmFilePath)) {
  try {
    __wasmFilePath = __nodePath.resolve('@rspack/binding-wasm32-wasi')
  } catch {
    throw new Error('Cannot find rspack.wasm32-wasi.wasm file, and @rspack/binding-wasm32-wasi package is not installed.')
  }
}

const { instance: __napiInstance, module: __wasiModule, napiModule: __napiModule } = __emnapiInstantiateNapiModuleSync(__nodeFs.readFileSync(__wasmFilePath), {
  context: __emnapiContext,
  asyncWorkPoolSize: (function() {
    const threadsSizeFromEnv = Number(process.env.NAPI_RS_ASYNC_WORK_POOL_SIZE ?? process.env.UV_THREADPOOL_SIZE)
    // NaN > 0 is false
    if (threadsSizeFromEnv > 0) {
      return threadsSizeFromEnv
    } else {
      return 4
    }
  })(),
  reuseWorker: true,
  wasi: __wasi,
  onCreateWorker() {
    const worker = new Worker(__nodePath.join(__dirname, 'wasi-worker.mjs'), {
      env: process.env,
    })
    worker.onmessage = ({ data }) => {
      __wasmCreateOnMessageForFsProxy(__nodeFs)(data)
    }

    // The main thread of Node.js waits for all the active handles before exiting.
    // But Rust threads are never waited without `thread::join`.
    // So here we hack the code of Node.js to prevent the workers from being referenced (active).
    // According to https://github.com/nodejs/node/blob/19e0d472728c79d418b74bddff588bea70a403d0/lib/internal/worker.js#L415,
    // a worker is consist of two handles: kPublicPort and kHandle.
    {
      const kPublicPort = Object.getOwnPropertySymbols(worker).find(s =>
        s.toString().includes("kPublicPort")
      );
      if (kPublicPort) {
        worker[kPublicPort].ref = () => {};
      }

      const kHandle = Object.getOwnPropertySymbols(worker).find(s =>
        s.toString().includes("kHandle")
      );
      if (kHandle) {
        worker[kHandle].ref = () => {};
      }

      worker.unref();
    }
    return worker
  },
  overwriteImports(importObject) {
    importObject.env = {
      ...importObject.env,
      ...importObject.napi,
      ...importObject.emnapi,
      memory: __sharedMemory,
    }
    return importObject
  },
  beforeInit({ instance }) {
    for (const name of Object.keys(instance.exports)) {
      if (name.startsWith('__napi_register__')) {
        instance.exports[name]()
      }
    }
  },
})
module.exports = __napiModule.exports
module.exports.Assets = __napiModule.exports.Assets
module.exports.AsyncDependenciesBlock = __napiModule.exports.AsyncDependenciesBlock
module.exports.Chunk = __napiModule.exports.Chunk
module.exports.ChunkGraph = __napiModule.exports.ChunkGraph
module.exports.ChunkGroup = __napiModule.exports.ChunkGroup
module.exports.Chunks = __napiModule.exports.Chunks
module.exports.CodeGenerationResult = __napiModule.exports.CodeGenerationResult
module.exports.CodeGenerationResults = __napiModule.exports.CodeGenerationResults
module.exports.ConcatenatedModule = __napiModule.exports.ConcatenatedModule
module.exports.ContextModule = __napiModule.exports.ContextModule
module.exports.Dependency = __napiModule.exports.Dependency
module.exports.Diagnostics = __napiModule.exports.Diagnostics
module.exports.EntryDataDto = __napiModule.exports.EntryDataDto
module.exports.EntryDataDTO = __napiModule.exports.EntryDataDTO
module.exports.EntryDependency = __napiModule.exports.EntryDependency
module.exports.EntryOptionsDto = __napiModule.exports.EntryOptionsDto
module.exports.EntryOptionsDTO = __napiModule.exports.EntryOptionsDTO
module.exports.ExternalModule = __napiModule.exports.ExternalModule
module.exports.JsCompilation = __napiModule.exports.JsCompilation
module.exports.JsCompiler = __napiModule.exports.JsCompiler
module.exports.JsContextModuleFactoryAfterResolveData = __napiModule.exports.JsContextModuleFactoryAfterResolveData
module.exports.JsContextModuleFactoryBeforeResolveData = __napiModule.exports.JsContextModuleFactoryBeforeResolveData
module.exports.JsDependencies = __napiModule.exports.JsDependencies
module.exports.JsEntries = __napiModule.exports.JsEntries
module.exports.JsExportsInfo = __napiModule.exports.JsExportsInfo
module.exports.JsModuleGraph = __napiModule.exports.JsModuleGraph
module.exports.JsResolver = __napiModule.exports.JsResolver
module.exports.JsResolverFactory = __napiModule.exports.JsResolverFactory
module.exports.JsStats = __napiModule.exports.JsStats
module.exports.KnownBuildInfo = __napiModule.exports.KnownBuildInfo
module.exports.Module = __napiModule.exports.Module
module.exports.ModuleGraphConnection = __napiModule.exports.ModuleGraphConnection
module.exports.NativeWatcher = __napiModule.exports.NativeWatcher
module.exports.NativeWatchResult = __napiModule.exports.NativeWatchResult
module.exports.NormalModule = __napiModule.exports.NormalModule
module.exports.RawExternalItemFnCtx = __napiModule.exports.RawExternalItemFnCtx
module.exports.ReadonlyResourceData = __napiModule.exports.ReadonlyResourceData
module.exports.ResolverFactory = __napiModule.exports.ResolverFactory
module.exports.Sources = __napiModule.exports.Sources
module.exports.VirtualFileStore = __napiModule.exports.VirtualFileStore
module.exports.JsVirtualFileStore = __napiModule.exports.JsVirtualFileStore
module.exports.async = __napiModule.exports.async
module.exports.BuiltinPluginName = __napiModule.exports.BuiltinPluginName
module.exports.cleanupGlobalTrace = __napiModule.exports.cleanupGlobalTrace
module.exports.EnforceExtension = __napiModule.exports.EnforceExtension
module.exports.EXPECTED_RSPACK_CORE_VERSION = __napiModule.exports.EXPECTED_RSPACK_CORE_VERSION
module.exports.formatDiagnostic = __napiModule.exports.formatDiagnostic
module.exports.JsLoaderState = __napiModule.exports.JsLoaderState
module.exports.JsRspackSeverity = __napiModule.exports.JsRspackSeverity
module.exports.loadBrowserslist = __napiModule.exports.loadBrowserslist
module.exports.minify = __napiModule.exports.minify
module.exports.minifySync = __napiModule.exports.minifySync
module.exports.RawJavascriptParserCommonjsExports = __napiModule.exports.RawJavascriptParserCommonjsExports
module.exports.RawRuleSetConditionType = __napiModule.exports.RawRuleSetConditionType
module.exports.registerGlobalTrace = __napiModule.exports.registerGlobalTrace
module.exports.RegisterJsTapKind = __napiModule.exports.RegisterJsTapKind
module.exports.sync = __napiModule.exports.sync
module.exports.syncTraceEvent = __napiModule.exports.syncTraceEvent
module.exports.transform = __napiModule.exports.transform
module.exports.transformSync = __napiModule.exports.transformSync
