/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NodeFs {
  writeFile: (...args: any[]) => any
  mkdir: (...args: any[]) => any
  mkdirp: (...args: any[]) => any
}
export type TestFS = TestFs
export class TestFs {
  constructor(fs: NodeFs)
  write(file: string, data: Array<number>): void
  mkdir(file: string): void
  mkdirp(file: string): void
}
