/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NodeFs {
  writeFile: (...args: any[]) => any
  mkdir: (...args: any[]) => any
  mkdirp: (...args: any[]) => any
}
export type TestFS = TestFs
export class TestFs {
  constructor(fs: NodeFs)
  writeSync(file: string, data: Buffer): void
  mkdirSync(file: string): void
  mkdirpSync(file: string): void
}
