/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ThreadsafeNodeFs {
  writeFile: (...args: any[]) => any
  mkdir: (...args: any[]) => any
  mkdirp: (...args: any[]) => any
}
export interface NodeFs {
  writeFile: (...args: any[]) => any
  mkdir: (...args: any[]) => any
  mkdirp: (...args: any[]) => any
}
export type TestFS = TestFs
export class TestFs {
  constructor(fs: NodeFS)
  writeSync(file: string, data: Buffer): void
  mkdirSync(file: string): void
  mkdirpSync(file: string): void
}
export type TestThreadsafeFS = TestThreadsafeFs
export class TestThreadsafeFs {
  constructor(fs: ThreadsafeNodeFS)
  write(file: string, data: Buffer): Promise<void>
  mkdir(file: string): Promise<void>
  mkdirp(file: string): Promise<void>
}
