const fs = require("fs")
const path = require("path")
const diff = require('jest-diff')

let dirname = path.resolve(__dirname, "../__snapshots__/")
const snapOrBakList = fs.readdirSync(dirname)
console.log(snapOrBakList)

let bakList = snapOrBakList.filter(item => item.endsWith('.bak'));

bakList.forEach(backupFileName => {
	// find snapshot generated by rspack
	let snapfileName = backupFileName.slice(0, -4)
	let backupContent  = fs.readFileSync(path.resolve(dirname, backupFileName)).toString()
	let snapContent = "" // content could be empty string when the whole snapshot test has been ignored

	if (snapOrBakList.includes(snapfileName)) {
		snapContent = fs.readFileSync(path.resolve(dirname, snapfileName)).toString()
	}
	let diffResult = diff.diff(backupContent, snapContent, {
		expand: false
	});
	fs.writeFileSync(path.resolve(dirname, `${snapfileName}.diff`), diffResult)
})




      //  Cli.basictest.js.snap
      //  ConfigTestCases.basictest.js.snap.bak
      //  StatsTestCases.basictest.js.snap.bak
      //  target-browserslist.unittest.js.snap
