use std::{
  collections::{BTreeMap, BTreeSet},
  fmt, fs,
};

use rspack_error::{Result, error};
use rspack_paths::Utf8PathBuf;
use serde::Deserialize;
use unicode_width::UnicodeWidthStr;

#[derive(Debug, Deserialize)]
struct ChartsReport {
  rspack_trace_layer: String,
  output_format: String,
  description: String,
  time_elapsed: String,
  total_elapsed_ns: u64,
  percentiles: Vec<u8>,
  data: Vec<ChartsEntry>,
}

#[derive(Debug, Clone, Deserialize)]
struct ChartsEntry {
  name: String,
  calls: u64,
  avg_raw: u64,
  percentiles_raw: BTreeMap<String, u64>,
  total_raw: u64,
  percent_total_raw: u64,
}

#[derive(Debug, Clone)]
enum MetricDiff {
  Calls(u64, u64),
  DurationNs(u64, u64),
  Percentage(u64, u64),
}

impl MetricDiff {
  fn format(&self) -> String {
    match self {
      MetricDiff::Calls(before, after) => {
        format!(
          "{before} -> {after} ({:+.1}%)",
          percentage_diff(*before, *after)
        )
      }
      MetricDiff::DurationNs(before, after) => format!(
        "{} -> {} ({:+.1}%)",
        format_duration_ns(*before),
        format_duration_ns(*after),
        percentage_diff(*before, *after)
      ),
      MetricDiff::Percentage(before, after) => format!(
        "{:.2}% -> {:.2}% ({:+.1}%)",
        *before as f64 / 100.0,
        *after as f64 / 100.0,
        percentage_diff(*before, *after)
      ),
    }
  }
}

impl fmt::Display for MetricDiff {
  fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
    write!(f, "{}", self.format())
  }
}

#[derive(Debug)]
struct FunctionDiff {
  function_name: String,
  importance: u64,
  cells: Vec<String>,
}

pub fn bench_diff(before_path: Utf8PathBuf, after_path: Utf8PathBuf) -> Result<String> {
  let before = load_report(&before_path)?;
  let after = load_report(&after_path)?;
  validate_reports(&before, &after)?;

  Ok(render_bench_diff(&before, &after))
}

fn load_report(path: &Utf8PathBuf) -> Result<ChartsReport> {
  let content = fs::read_to_string(path).map_err(|error| {
    error!(
      "Failed to read hotpath report from {}: {}",
      path.as_str(),
      error
    )
  })?;

  serde_json::from_str(&content).map_err(|error| {
    error!(
      "Failed to parse hotpath report JSON from {}: {}",
      path.as_str(),
      error
    )
  })
}

fn validate_reports(before: &ChartsReport, after: &ChartsReport) -> Result<()> {
  for (label, report) in [("before", before), ("after", after)] {
    if report.rspack_trace_layer != "hotpath" {
      return Err(error!(
        "Expected {label} report to be generated by hotpath layer, got {}",
        report.rspack_trace_layer
      ));
    }

    if report.output_format != "json" {
      return Err(error!(
        "Expected {label} report to use json output, got {}",
        report.output_format
      ));
    }
  }

  if before.percentiles != after.percentiles {
    return Err(error!(
      "Percentiles do not match: before={:?}, after={:?}",
      before.percentiles, after.percentiles
    ));
  }

  Ok(())
}

fn render_bench_diff(before: &ChartsReport, after: &ChartsReport) -> String {
  let function_diffs = build_function_diffs(before, after);
  let headers = build_headers(&before.percentiles);
  let rows = function_diffs
    .into_iter()
    .map(|diff| diff.cells)
    .collect::<Vec<_>>();

  let mut output = String::new();
  output.push_str("bench-diff - hotpath JSON comparison\n");
  output.push_str(&format!("Description: {}\n", before.description));
  output.push_str(&format!(
    "Overall elapsed: {} -> {} ({:+.1}%)\n",
    before.time_elapsed,
    after.time_elapsed,
    percentage_diff(before.total_elapsed_ns, after.total_elapsed_ns)
  ));
  output.push_str(&render_table(&headers, &rows));
  output.push('\n');
  output
}

fn build_function_diffs(before: &ChartsReport, after: &ChartsReport) -> Vec<FunctionDiff> {
  let before_map = before
    .data
    .iter()
    .map(|entry| (entry.name.as_str(), entry))
    .collect::<BTreeMap<_, _>>();
  let after_map = after
    .data
    .iter()
    .map(|entry| (entry.name.as_str(), entry))
    .collect::<BTreeMap<_, _>>();

  let names = before_map
    .keys()
    .chain(after_map.keys())
    .copied()
    .collect::<BTreeSet<_>>();

  let mut diffs = names
    .into_iter()
    .map(|name| {
      let before_entry = before_map.get(name).copied();
      let after_entry = after_map.get(name).copied();
      build_function_diff(name, before_entry, after_entry, &before.percentiles)
    })
    .collect::<Vec<_>>();

  diffs.sort_by(|left, right| {
    right
      .importance
      .cmp(&left.importance)
      .then_with(|| left.function_name.cmp(&right.function_name))
  });

  diffs
}

fn build_function_diff(
  function_name: &str,
  before: Option<&ChartsEntry>,
  after: Option<&ChartsEntry>,
  percentiles: &[u8],
) -> FunctionDiff {
  let is_new = before.is_none();
  let is_removed = after.is_none();
  let before_entry = before.cloned().unwrap_or_else(|| zero_entry(function_name));
  let after_entry = after.cloned().unwrap_or_else(|| zero_entry(function_name));
  let display_name = if is_new {
    format!("[new] {}", shorten_name(function_name))
  } else if is_removed {
    format!("[removed] {}", shorten_name(function_name))
  } else {
    shorten_name(function_name)
  };

  let mut cells = vec![
    display_name,
    MetricDiff::DurationNs(before_entry.avg_raw, after_entry.avg_raw).to_string(),
  ];

  for percentile in percentiles {
    let key = format!("p{percentile}");
    let before_raw = before_entry
      .percentiles_raw
      .get(&key)
      .copied()
      .unwrap_or_default();
    let after_raw = after_entry
      .percentiles_raw
      .get(&key)
      .copied()
      .unwrap_or_default();
    cells.push(MetricDiff::DurationNs(before_raw, after_raw).to_string());
  }

  cells.push(MetricDiff::DurationNs(before_entry.total_raw, after_entry.total_raw).to_string());
  cells.push(
    MetricDiff::Percentage(
      before_entry.percent_total_raw,
      after_entry.percent_total_raw,
    )
    .to_string(),
  );
  cells.push(MetricDiff::Calls(before_entry.calls, after_entry.calls).to_string());

  FunctionDiff {
    function_name: function_name.to_string(),
    importance: before_entry
      .percent_total_raw
      .max(after_entry.percent_total_raw),
    cells,
  }
}

fn zero_entry(function_name: &str) -> ChartsEntry {
  ChartsEntry {
    name: function_name.to_string(),
    calls: 0,
    avg_raw: 0,
    percentiles_raw: BTreeMap::default(),
    total_raw: 0,
    percent_total_raw: 0,
  }
}

fn build_headers(percentiles: &[u8]) -> Vec<String> {
  let mut headers = vec!["Function".to_string(), "Avg".to_string()];

  headers.extend(
    percentiles
      .iter()
      .map(|percentile| format!("P{percentile}")),
  );
  headers.push("Total".to_string());
  headers.push("% Total".to_string());
  headers.push("Calls".to_string());
  headers
}

fn percentage_diff(before: u64, after: u64) -> f64 {
  if before == 0 {
    if after == 0 { 0.0 } else { 100.0 }
  } else {
    ((after as f64 - before as f64) / before as f64) * 100.0
  }
}

fn shorten_name(name: &str) -> String {
  let parts: Vec<&str> = name.split("::").collect();
  if parts.len() > 2 {
    return parts[parts.len() - 2..].join("::");
  }

  name.to_string()
}

fn format_duration_ns(ns: u64) -> String {
  if ns < 1_000 {
    format!("{ns} ns")
  } else if ns < 1_000_000 {
    format!("{:.2} us", ns as f64 / 1_000.0)
  } else if ns < 1_000_000_000 {
    format!("{:.2} ms", ns as f64 / 1_000_000.0)
  } else {
    format!("{:.2} s", ns as f64 / 1_000_000_000.0)
  }
}

fn render_table(headers: &[String], rows: &[Vec<String>]) -> String {
  let mut widths = headers
    .iter()
    .map(|header| UnicodeWidthStr::width(header.as_str()))
    .collect::<Vec<_>>();

  for row in rows {
    for (index, cell) in row.iter().enumerate() {
      widths[index] = widths[index].max(UnicodeWidthStr::width(cell.as_str()));
    }
  }

  let mut output = String::new();
  output.push_str(&render_separator(&widths));
  output.push_str(&render_row(headers, &widths, false));
  output.push_str(&render_separator(&widths));

  for row in rows {
    output.push_str(&render_row(row, &widths, true));
  }

  output.push_str(&render_separator(&widths));
  output
}

fn render_separator(widths: &[usize]) -> String {
  let mut output = String::new();
  output.push('+');
  for width in widths {
    output.push_str(&"-".repeat(width.saturating_add(2)));
    output.push('+');
  }
  output.push('\n');
  output
}

fn render_row(cells: &[String], widths: &[usize], align_numbers_right: bool) -> String {
  let mut output = String::new();
  output.push('|');

  for (index, cell) in cells.iter().enumerate() {
    output.push(' ');

    let width = widths[index];
    let cell_width = UnicodeWidthStr::width(cell.as_str());
    let padding = width.saturating_sub(cell_width);
    let align_right = align_numbers_right && index > 0;

    if align_right {
      output.push_str(&" ".repeat(padding));
      output.push_str(cell);
    } else {
      output.push_str(cell);
      output.push_str(&" ".repeat(padding));
    }

    output.push(' ');
    output.push('|');
  }

  output.push('\n');
  output
}

#[cfg(test)]
mod tests {
  use std::{
    collections::BTreeMap,
    fs,
    time::{SystemTime, UNIX_EPOCH},
  };

  use rspack_paths::Utf8PathBuf;

  use super::{ChartsEntry, ChartsReport, bench_diff, build_function_diffs, render_bench_diff};

  fn make_report(total_elapsed_ns: u64, entries: Vec<ChartsEntry>) -> ChartsReport {
    ChartsReport {
      rspack_trace_layer: "hotpath".to_string(),
      output_format: "json".to_string(),
      description: "Aggregated tracing spans (avg, p95, total)".to_string(),
      time_elapsed: super::format_duration_ns(total_elapsed_ns),
      total_elapsed_ns,
      percentiles: vec![95],
      data: entries,
    }
  }

  fn make_entry(
    name: &str,
    calls: u64,
    avg_raw: u64,
    p95_raw: u64,
    total_raw: u64,
    percent_total_raw: u64,
  ) -> ChartsEntry {
    ChartsEntry {
      name: name.to_string(),
      calls,
      avg_raw,
      percentiles_raw: BTreeMap::from([("p95".to_string(), p95_raw)]),
      total_raw,
      percent_total_raw,
    }
  }

  #[test]
  fn should_render_bench_diff_table() {
    let before = make_report(
      10_000_000,
      vec![make_entry(
        "rspack_core::compiler::make",
        1,
        2_000_000,
        3_000_000,
        4_000_000,
        4000,
      )],
    );
    let after = make_report(
      12_000_000,
      vec![make_entry(
        "rspack_core::compiler::make",
        2,
        3_000_000,
        4_000_000,
        6_000_000,
        5000,
      )],
    );

    let output = render_bench_diff(&before, &after);

    assert!(output.contains("bench-diff - hotpath JSON comparison"));
    assert!(output.contains("Overall elapsed: 10.00 ms -> 12.00 ms (+20.0%)"));
    assert!(output.contains("| Function"));
    assert!(output.contains("| Avg"));
    assert!(output.contains("| Calls"));
    assert!(output.contains("compiler::make"));
    assert!(output.contains("1 -> 2 (+100.0%)"));
    assert!(output.contains("4.00 ms -> 6.00 ms (+50.0%)"));
  }

  #[test]
  fn should_mark_new_and_removed_functions() {
    let before = make_report(
      10_000_000,
      vec![make_entry("rspack_core::compiler::old", 1, 1, 1, 2, 2000)],
    );
    let after = make_report(
      10_000_000,
      vec![make_entry("rspack_core::compiler::new", 1, 1, 1, 3, 3000)],
    );

    let diffs = build_function_diffs(&before, &after);

    assert_eq!(diffs[0].cells[0], "[new] compiler::new");
    assert_eq!(diffs[1].cells[0], "[removed] compiler::old");
  }

  #[test]
  fn should_fail_on_non_hotpath_json() {
    let unique = SystemTime::now()
      .duration_since(UNIX_EPOCH)
      .expect("time should be after unix epoch")
      .as_nanos();
    let dir = std::env::temp_dir().join(format!("rspack-tools-bench-diff-{unique}"));
    fs::create_dir_all(&dir).expect("should create tempdir");
    let before_path = Utf8PathBuf::from_path_buf(dir.join("before.json")).expect("utf8");
    let after_path = Utf8PathBuf::from_path_buf(dir.join("after.json")).expect("utf8");

    fs::write(
      &before_path,
      r#"{"rspack_trace_layer":"perfetto","output_format":"json","description":"x","time_elapsed":"1 ms","total_elapsed_ns":1,"percentiles":[95],"data":[]}"#,
    )
    .expect("write before");
    fs::write(
      &after_path,
      r#"{"rspack_trace_layer":"hotpath","output_format":"json","description":"x","time_elapsed":"1 ms","total_elapsed_ns":1,"percentiles":[95],"data":[]}"#,
    )
    .expect("write after");

    let error = bench_diff(before_path, after_path).expect_err("should fail");
    assert!(error.to_string().contains("hotpath layer"));

    fs::remove_dir_all(&dir).expect("cleanup tempdir");
  }
}
