name: nodejs and pnpm setup

description: Install Node.js with pnpm global cache

inputs:
  node-version:
    default: '22'
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Install Node.js
      if: ${{ startsWith(runner.name, 'rspack-darwin-') }}
      uses: rstackjs/setup-node@cc72f1c242ef8813f650223fbae3c29d450ae29e # v0.0.1
      with:
        registry-url: https://registry.npmmirror.com
        node-version: ${{ inputs.node-version }}

    - name: Install Node.js
      if: ${{ !startsWith(runner.name, 'rspack-darwin-') }}
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install pnpm
      uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
      with:
        standalone: ${{ startsWith(inputs.node-version, '20') }}
