name: nodejs and pnpm setup

description: Install Node.js and pnpm

inputs:
  node-version:
    default: '22'
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Install Node.js
      if: ${{ startsWith(runner.name, 'rspack-darwin-') }}
      uses: rstackjs/setup-node@3ff0cf4618911930967df3bf1afa93fda4abaf1b # v0.0.2
      with:
        registry-url: https://registry.npmmirror.com
        node-version: ${{ inputs.node-version }}

    - name: Install Node.js
      if: ${{ !startsWith(runner.name, 'rspack-darwin-') }}
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install pnpm
      uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      with:
        # E2E containers mount the tool cache to access Node.js and pnpm.
        dest: ${{ runner.tool_cache }}/pnpm
