export {
	ANIMATION_MODULE_TYPE,
	APP_BOOTSTRAP_LISTENER,
	APP_ID,
	APP_INITIALIZER,
	ApplicationInitStatus,
	ApplicationModule,
	ApplicationRef,
	Attribute,
	COMPILER_OPTIONS,
	CSP_NONCE,
	CUSTOM_ELEMENTS_SCHEMA,
	ChangeDetectionStrategy,
	ChangeDetectorRef,
	Compiler,
	CompilerFactory,
	Component,
	ComponentFactory$1 as ComponentFactory,
	ComponentFactoryResolver$1 as ComponentFactoryResolver,
	ComponentRef$1 as ComponentRef,
	ContentChild,
	ContentChildren,
	DEFAULT_CURRENCY_CODE,
	DebugElement,
	DebugEventListener,
	DebugNode,
	DefaultIterableDiffer,
	DestroyRef,
	Directive,
	ENVIRONMENT_INITIALIZER,
	ElementRef,
	EmbeddedViewRef,
	EnvironmentInjector,
	ErrorHandler,
	EventEmitter,
	Host,
	HostBinding,
	HostListener,
	INJECTOR,
	Inject,
	InjectFlags,
	Injectable,
	InjectionToken,
	Injector,
	Input,
	IterableDiffers,
	KeyValueDiffers,
	LOCALE_ID,
	MissingTranslationStrategy,
	ModuleWithComponentFactories,
	NO_ERRORS_SCHEMA,
	NgModule,
	NgModuleFactory$1 as NgModuleFactory,
	NgModuleRef$1 as NgModuleRef,
	NgProbeToken,
	NgZone,
	Optional,
	Output,
	PACKAGE_ROOT_URL,
	PLATFORM_ID,
	PLATFORM_INITIALIZER,
	Pipe,
	PlatformRef,
	Query,
	QueryList,
	Renderer2,
	RendererFactory2,
	RendererStyleFlags2,
	Sanitizer,
	// SecurityContext,
	Self,
	SimpleChange,
	SkipSelf,
	TRANSLATIONS,
	TRANSLATIONS_FORMAT,
	TemplateRef,
	Testability,
	TestabilityRegistry,
	// TransferState,
	Type,
	VERSION,
	Version,
	ViewChild,
	ViewChildren,
	ViewContainerRef,
	ViewEncapsulation$1 as ViewEncapsulation,
	ViewRef,
	asNativeElements,
	assertInInjectionContext,
	assertPlatform,
	computed,
	createComponent,
	createEnvironmentInjector,
	createNgModule,
	createNgModuleRef,
	createPlatform,
	createPlatformFactory,
	defineInjectable,
	destroyPlatform,
	effect,
	enableProdMode,
	forwardRef,
	getDebugNode,
	getModuleFactory,
	getNgModuleById,
	getPlatform,
	importProvidersFrom,
	inject,
	isDevMode,
	isSignal,
	isStandalone,
	makeEnvironmentProviders,
	// makeStateKey,
	mergeApplicationConfig,
	platformCore,
	provideZoneChangeDetection,
	reflectComponentType,
	resolveForwardRef,
	runInInjectionContext,
	setTestabilityGetter,
	signal,
	untracked,
	ALLOW_MULTIPLE_PLATFORMS as ɵALLOW_MULTIPLE_PLATFORMS,
	ComponentFactory$1 as ɵComponentFactory,
	Console as ɵConsole,
	DEFAULT_LOCALE_ID as ɵDEFAULT_LOCALE_ID,
	ENABLED_SSR_FEATURES as ɵENABLED_SSR_FEATURES,
	INJECTOR_SCOPE as ɵINJECTOR_SCOPE,
	IS_HYDRATION_DOM_REUSE_ENABLED as ɵIS_HYDRATION_DOM_REUSE_ENABLED,
	InitialRenderPendingTasks as ɵInitialRenderPendingTasks,
	LContext as ɵLContext,
	LifecycleHooksFeature as ɵLifecycleHooksFeature,
	LocaleDataIndex as ɵLocaleDataIndex,
	NG_COMP_DEF as ɵNG_COMP_DEF,
	NG_DIR_DEF as ɵNG_DIR_DEF,
	NG_ELEMENT_ID as ɵNG_ELEMENT_ID,
	NG_INJ_DEF as ɵNG_INJ_DEF,
	NG_MOD_DEF as ɵNG_MOD_DEF,
	NG_PIPE_DEF as ɵNG_PIPE_DEF,
	NG_PROV_DEF as ɵNG_PROV_DEF,
	NOT_FOUND_CHECK_ONLY_ELEMENT_INJECTOR as ɵNOT_FOUND_CHECK_ONLY_ELEMENT_INJECTOR,
	NO_CHANGE as ɵNO_CHANGE,
	NgModuleFactory as ɵNgModuleFactory,
	NoopNgZone as ɵNoopNgZone,
	ReflectionCapabilities as ɵReflectionCapabilities,
	ComponentFactory as ɵRender3ComponentFactory,
	ComponentRef as ɵRender3ComponentRef,
	NgModuleRef as ɵRender3NgModuleRef,
	RuntimeError as ɵRuntimeError,
	TESTABILITY as ɵTESTABILITY,
	TESTABILITY_GETTER as ɵTESTABILITY_GETTER,
	ViewRef$1 as ɵViewRef,
	// XSS_SECURITY_URL as ɵXSS_SECURITY_URL,
	// _sanitizeHtml as ɵ_sanitizeHtml,
	_sanitizeUrl as ɵ_sanitizeUrl,
	// allowSanitizationBypassAndThrow as ɵallowSanitizationBypassAndThrow,
	annotateForHydration as ɵannotateForHydration,
	// bypassSanitizationTrustHtml as ɵbypassSanitizationTrustHtml,
	// bypassSanitizationTrustResourceUrl as ɵbypassSanitizationTrustResourceUrl,
	// bypassSanitizationTrustScript as ɵbypassSanitizationTrustScript,
	// bypassSanitizationTrustStyle as ɵbypassSanitizationTrustStyle,
	// bypassSanitizationTrustUrl as ɵbypassSanitizationTrustUrl,
	clearResolutionOfComponentResourcesQueue as ɵclearResolutionOfComponentResourcesQueue,
	coerceToBoolean as ɵcoerceToBoolean,
	compileComponent as ɵcompileComponent,
	compileDirective as ɵcompileDirective,
	compileNgModule as ɵcompileNgModule,
	compileNgModuleDefs as ɵcompileNgModuleDefs,
	compileNgModuleFactory as ɵcompileNgModuleFactory,
	compilePipe as ɵcompilePipe,
	convertToBitFlags as ɵconvertToBitFlags,
	createInjector as ɵcreateInjector,
	defaultIterableDiffers as ɵdefaultIterableDiffers,
	defaultKeyValueDiffers as ɵdefaultKeyValueDiffers,
	detectChanges as ɵdetectChanges,
	devModeEqual as ɵdevModeEqual,
	escapeTransferStateContent as ɵescapeTransferStateContent,
	findLocaleData as ɵfindLocaleData,
	flushModuleScopingQueueAsMuchAsPossible as ɵflushModuleScopingQueueAsMuchAsPossible,
	// formatRuntimeError as ɵformatRuntimeError,
	getDebugNode as ɵgetDebugNode,
	getDirectives as ɵgetDirectives,
	getHostElement as ɵgetHostElement,
	getInjectableDef as ɵgetInjectableDef,
	getLContext as ɵgetLContext,
	getLocaleCurrencyCode as ɵgetLocaleCurrencyCode,
	getLocalePluralCase as ɵgetLocalePluralCase,
	getSanitizationBypassType as ɵgetSanitizationBypassType,
	ɵgetUnknownElementStrictMode,
	ɵgetUnknownPropertyStrictMode,
	_global as ɵglobal,
	injectChangeDetectorRef as ɵinjectChangeDetectorRef,
	internalCreateApplication as ɵinternalCreateApplication,
	isBoundToModule as ɵisBoundToModule,
	isEnvironmentProviders as ɵisEnvironmentProviders,
	isInjectable as ɵisInjectable,
	isNgModule as ɵisNgModule,
	isPromise as ɵisPromise,
	isSubscribable as ɵisSubscribable,
	noSideEffects as ɵnoSideEffects,
	patchComponentDefWithScope as ɵpatchComponentDefWithScope,
	publishDefaultGlobalUtils$1 as ɵpublishDefaultGlobalUtils,
	publishGlobalUtil as ɵpublishGlobalUtil,
	registerLocaleData as ɵregisterLocaleData,
	resetCompiledComponents as ɵresetCompiledComponents,
	resetJitOptions as ɵresetJitOptions,
	resolveComponentResources as ɵresolveComponentResources,
	setAllowDuplicateNgModuleIdsForTest as ɵsetAllowDuplicateNgModuleIdsForTest,
	setAlternateWeakRefImpl as ɵsetAlternateWeakRefImpl,
	setClassMetadata as ɵsetClassMetadata,
	setCurrentInjector as ɵsetCurrentInjector,
	setDocument as ɵsetDocument,
	setLocaleId as ɵsetLocaleId,
	ɵsetUnknownElementStrictMode,
	ɵsetUnknownPropertyStrictMode,
	store as ɵstore,
	stringify as ɵstringify,
	transitiveScopesFor as ɵtransitiveScopesFor,
	unescapeTransferStateContent as ɵunescapeTransferStateContent,
	unregisterAllLocaleData as ɵunregisterLocaleData,
	// unwrapSafeValue as ɵunwrapSafeValue,
	withDomHydration as ɵwithDomHydration,
	ɵɵCopyDefinitionFeature,
	FactoryTarget as ɵɵFactoryTarget,
	ɵɵHostDirectivesFeature,
	ɵɵInheritDefinitionFeature,
	ɵɵNgOnChangesFeature,
	ɵɵProvidersFeature,
	ɵɵStandaloneFeature,
	ɵɵadvance,
	ɵɵattribute,
	ɵɵattributeInterpolate1,
	ɵɵattributeInterpolate2,
	ɵɵattributeInterpolate3,
	ɵɵattributeInterpolate4,
	ɵɵattributeInterpolate5,
	ɵɵattributeInterpolate6,
	ɵɵattributeInterpolate7,
	ɵɵattributeInterpolate8,
	ɵɵattributeInterpolateV,
	ɵɵclassMap,
	ɵɵclassMapInterpolate1,
	ɵɵclassMapInterpolate2,
	ɵɵclassMapInterpolate3,
	ɵɵclassMapInterpolate4,
	ɵɵclassMapInterpolate5,
	ɵɵclassMapInterpolate6,
	ɵɵclassMapInterpolate7,
	ɵɵclassMapInterpolate8,
	ɵɵclassMapInterpolateV,
	ɵɵclassProp,
	ɵɵcontentQuery,
	ɵɵdefineComponent,
	ɵɵdefineDirective,
	ɵɵdefineInjectable,
	ɵɵdefineInjector,
	ɵɵdefineNgModule,
	ɵɵdefinePipe,
	ɵɵdirectiveInject,
	ɵɵdisableBindings,
	ɵɵelement,
	ɵɵelementContainer,
	ɵɵelementContainerEnd,
	ɵɵelementContainerStart,
	ɵɵelementEnd,
	ɵɵelementStart,
	ɵɵenableBindings,
	ɵɵgetCurrentView,
	ɵɵgetInheritedFactory,
	ɵɵhostProperty,
	ɵɵi18n,
	ɵɵi18nApply,
	ɵɵi18nAttributes,
	ɵɵi18nEnd,
	ɵɵi18nExp,
	ɵɵi18nPostprocess,
	ɵɵi18nStart,
	ɵɵinject,
	ɵɵinjectAttribute,
	ɵɵinvalidFactory,
	ɵɵinvalidFactoryDep,
	ɵɵlistener,
	ɵɵloadQuery,
	ɵɵnamespaceHTML,
	ɵɵnamespaceMathML,
	ɵɵnamespaceSVG,
	ɵɵnextContext,
	ɵɵngDeclareClassMetadata,
	ɵɵngDeclareComponent,
	ɵɵngDeclareDirective,
	ɵɵngDeclareFactory,
	ɵɵngDeclareInjectable,
	ɵɵngDeclareInjector,
	ɵɵngDeclareNgModule,
	ɵɵngDeclarePipe,
	ɵɵpipe,
	ɵɵpipeBind1,
	ɵɵpipeBind2,
	ɵɵpipeBind3,
	ɵɵpipeBind4,
	ɵɵpipeBindV,
	ɵɵprojection,
	ɵɵprojectionDef,
	ɵɵproperty,
	ɵɵpropertyInterpolate,
	ɵɵpropertyInterpolate1,
	ɵɵpropertyInterpolate2,
	ɵɵpropertyInterpolate3,
	ɵɵpropertyInterpolate4,
	ɵɵpropertyInterpolate5,
	ɵɵpropertyInterpolate6,
	ɵɵpropertyInterpolate7,
	ɵɵpropertyInterpolate8,
	ɵɵpropertyInterpolateV,
	ɵɵpureFunction0,
	ɵɵpureFunction1,
	ɵɵpureFunction2,
	ɵɵpureFunction3,
	ɵɵpureFunction4,
	ɵɵpureFunction5,
	ɵɵpureFunction6,
	ɵɵpureFunction7,
	ɵɵpureFunction8,
	ɵɵpureFunctionV,
	ɵɵqueryRefresh,
	ɵɵreference,
	registerNgModuleType as ɵɵregisterNgModuleType,
	ɵɵresetView,
	ɵɵresolveBody,
	ɵɵresolveDocument,
	ɵɵresolveWindow,
	ɵɵrestoreView,
	ɵɵsanitizeHtml,
	ɵɵsanitizeResourceUrl,
	ɵɵsanitizeScript,
	ɵɵsanitizeStyle,
	ɵɵsanitizeUrl,
	ɵɵsanitizeUrlOrResourceUrl,
	ɵɵsetComponentScope,
	ɵɵsetNgModuleScope,
	ɵɵstyleMap,
	ɵɵstyleMapInterpolate1,
	ɵɵstyleMapInterpolate2,
	ɵɵstyleMapInterpolate3,
	ɵɵstyleMapInterpolate4,
	ɵɵstyleMapInterpolate5,
	ɵɵstyleMapInterpolate6,
	ɵɵstyleMapInterpolate7,
	ɵɵstyleMapInterpolate8,
	ɵɵstyleMapInterpolateV,
	// ɵɵstyleProp,
	ɵɵstylePropInterpolate1,
	ɵɵstylePropInterpolate2,
	ɵɵstylePropInterpolate3,
	ɵɵstylePropInterpolate4,
	ɵɵstylePropInterpolate5,
	ɵɵstylePropInterpolate6,
	ɵɵstylePropInterpolate7,
	ɵɵstylePropInterpolate8,
	ɵɵstylePropInterpolateV,
	ɵɵsyntheticHostListener,
	ɵɵsyntheticHostProperty,
	ɵɵtemplate,
	ɵɵtemplateRefExtractor,
	ɵɵtext,
	ɵɵtextInterpolate,
	ɵɵtextInterpolate1,
	ɵɵtextInterpolate2,
	ɵɵtextInterpolate3,
	ɵɵtextInterpolate4,
	ɵɵtextInterpolate5,
	ɵɵtextInterpolate6,
	ɵɵtextInterpolate7,
	ɵɵtextInterpolate8,
	ɵɵtextInterpolateV,
	ɵɵtrustConstantHtml,
	ɵɵtrustConstantResourceUrl,
	ɵɵvalidateIframeAttribute,
	ɵɵviewQuery
};
