use std::{env, fs, path::Path};

// Regenerates the committed `src/generated.rs` from the workspace `Cargo.toml`
// and `package.json` so the version info stays visible in version control.
//
// It only writes when run from inside the rspack repository (detected by the
// presence of the root `package.json` and `[workspace]` `Cargo.toml`). When
// `rspack_workspace` is built as a published dependency those files are absent,
// so the committed `generated.rs` is used untouched — a build script must never
// write outside `OUT_DIR` in that case (the registry source dir is read-only).
fn main() {
  let Ok(manifest_dir) = env::var("CARGO_MANIFEST_DIR") else {
    return;
  };
  let manifest_dir = Path::new(&manifest_dir);
  let Some(workspace_root) = manifest_dir.ancestors().nth(2) else {
    return;
  };

  let cargo_toml_path = workspace_root.join("Cargo.toml");
  let package_json_path = workspace_root.join("package.json");
  if !cargo_toml_path.exists() || !package_json_path.exists() {
    return;
  }

  let generated_path = manifest_dir.join("src/generated.rs");
  println!("cargo::rerun-if-changed={}", cargo_toml_path.display());
  println!("cargo::rerun-if-changed={}", package_json_path.display());
  // Also rerun when generated.rs itself is edited, so a manual change is reasserted.
  println!("cargo::rerun-if-changed={}", generated_path.display());

  let Some(content) = generate(&cargo_toml_path, &package_json_path) else {
    println!(
      "cargo::warning=rspack_workspace: could not read workspace versions; src/generated.rs left unchanged"
    );
    return;
  };

  // Only write on change to avoid dirtying the working tree and recompiles.
  if fs::read_to_string(&generated_path).unwrap_or_default() == content {
    return;
  }
  if let Err(e) = fs::write(&generated_path, &content) {
    println!(
      "cargo::warning=rspack_workspace: could not write src/generated.rs ({e}); using the committed file"
    );
  }
}

fn generate(cargo_toml_path: &Path, package_json_path: &Path) -> Option<String> {
  let manifest = cargo_toml::Manifest::from_str(&fs::read_to_string(cargo_toml_path).ok()?).ok()?;
  let workspace = manifest.workspace?;

  let workspace_version = workspace.package?.version?;

  let swc_core_version = match workspace.dependencies.get("swc_core")? {
    cargo_toml::Dependency::Simple(s) => s.to_owned(),
    // In workspace Cargo.toml, dependencies should be Simple/Detailed, not Inherited.
    cargo_toml::Dependency::Inherited(_) => return None,
    // Remove leading '=' from version string if present.
    cargo_toml::Dependency::Detailed(d) => {
      d.version.as_deref()?.trim_start_matches('=').to_string()
    }
  };

  let package_json: serde_json::Value =
    serde_json::from_str(&fs::read_to_string(package_json_path).ok()?).ok()?;
  let rspack_version = package_json["version"].as_str()?;

  Some(format!(
    r#"//! @generated by `build.rs` from the workspace `Cargo.toml` and `package.json`. Do not edit by hand.
/// The version of the `swc_core` package used in the current workspace.
pub const fn rspack_swc_core_version() -> &'static str {{
  "{swc_core_version}"
}}

/// The version of the JavaScript `@rspack/core` package.
pub const fn rspack_pkg_version() -> &'static str {{
  "{rspack_version}"
}}

/// The version of the Rust workspace in the root `Cargo.toml` of the repository.
pub const fn rspack_workspace_version() -> &'static str {{
  "{workspace_version}"
}}
"#
  ))
}
