[package]
authors.workspace       = true
categories.workspace    = true
description             = "Rspack workspace utilities"
documentation.workspace = true
edition.workspace       = true
homepage.workspace      = true
license.workspace       = true
name                    = "rspack_workspace"
repository.workspace    = true
version.workspace       = true

[build-dependencies]
cargo_toml = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true

[lib]
doctest = false
test    = false
