use rspack_intern::Atom;
use swc_next_ecma_ast::{
  AssignmentExpression, AwaitExpression, BinaryExpression, BindingIdentifier, CallExpression,
  ChainExpression, ClassElement, ConditionalExpression, Expr, ForOfStatement, IfStatement,
  ImportDeclaration, ImportExpression, LogicalExpression, MemberExpression, NewExpression, Program,
  Span, Stmt, ThisExpression, UnaryExpression, VariableDeclarator,
};

use crate::visitors::HookMemberExpression;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum JavascriptParserPluginHook {
  PreStatement,
  BlockPreStatement,
  TopLevelAwaitExpr,
  TopLevelForOfAwaitStmt,
  CanRename,
  Rename,
  Program,
  Statement,
  UnusedStatement,
  ModuleDeclaration,
  BlockPreModuleDeclaration,
  PreDeclarator,
  Evaluate,
  EvaluateTypeof,
  EvaluateCallExpression,
  EvaluateCallExpressionMember,
  EvaluateBinaryExpression,
  EvaluateIdentifier,
  CanCollectDestructuringAssignmentProperties,
  Pattern,
  Call,
  CallMemberChain,
  Member,
  MemberChain,
  UnhandledExpressionMemberChain,
  MemberChainOfCallMemberChain,
  CallMemberChainOfCallMemberChain,
  Typeof,
  ExpressionLogicalOperator,
  BinaryExpression,
  StatementIf,
  ClassExtendsExpression,
  ClassBodyElement,
  ClassBodyValue,
  Declarator,
  NewExpression,
  Identifier,
  This,
  Assign,
  AssignMemberChain,
  ImportCall,
  MetaProperty,
  Import,
  ImportSpecifier,
  ExportImport,
  Export,
  ExportImportSpecifier,
  ExportSpecifier,
  ExportExpression,
  OptionalChaining,
  ExpressionConditionalOperation,
  Finish,
  IsPure,
  ImportMetaPropertyInDestructuring,
}

impl JavascriptParserPluginHook {
  pub const COUNT: usize = Self::ImportMetaPropertyInDestructuring as usize + 1;
  pub const ALL_MASK: u64 = if Self::COUNT == u64::BITS as usize {
    u64::MAX
  } else {
    (1u64 << Self::COUNT) - 1
  };

  pub const fn mask(self) -> u64 {
    1u64 << (self as u8)
  }
}

const _: () = assert!(
  JavascriptParserPluginHook::COUNT <= 64,
  "The number of JavascriptParserPluginHook variants exceeds 64, which cannot be safely stored in a u64 bitmask."
);

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct JavascriptParserPluginHooks(u64);

impl JavascriptParserPluginHooks {
  pub const fn empty() -> Self {
    Self(0)
  }

  pub const fn all() -> Self {
    Self(JavascriptParserPluginHook::ALL_MASK)
  }

  pub const fn bits(self) -> u64 {
    self.0
  }

  pub const fn with(self, hook: JavascriptParserPluginHook) -> Self {
    Self(self.0 | hook.mask())
  }
}

use crate::{
  utils::eval::BasicEvaluatedExpression,
  visitors::{
    ClassDeclOrExpr, DestructuringAssignmentProperty, ExportDefaultDeclaration,
    ExportDefaultExpression, ExportImport, ExportLocal, ExportedVariableInfo,
    ExpressionExpressionInfo, Identifier, JavascriptParser, Statement, VariableDeclaration,
  },
};

type KeepRight = bool;

pub trait JavascriptParserPlugin<'p, 'a> {
  /// Used by the parser drive to precompute which hook paths this plugin
  /// actually implements.
  ///
  /// # Why this exists (performance)
  ///
  /// `JavaScriptParserPluginDrive` needs to call many hook methods while walking the AST.
  /// Calling every hook on every plugin would be very expensive.
  ///
  /// Instead, rspack precomputes a *hook mask* for each plugin at construction time:
  ///
  /// - Each plugin reports which hooks it actually implements via this method.
  /// - The drive groups plugins by hook up-front.
  /// - During parsing, the drive only iterates plugins that declared the current hook.
  ///
  /// This cuts a large amount of useless dynamic dispatch at runtime.
  ///
  /// # How to implement
  ///
  /// Do **NOT** implement this method manually.
  ///
  /// Use the proc-macro attribute `#[rspack_plugin_javascript::implemented_javascript_parser_hooks]`
  /// (or `#[rspack_macros::implemented_javascript_parser_hooks]` inside the workspace).
  /// The macro inspects the `impl<'p, 'a> JavascriptParserPlugin<'p, 'a> for ...` block and generates an
  /// efficient `implemented_hooks` implementation automatically.
  fn implemented_hooks(&self) -> JavascriptParserPluginHooks {
    // NOTE: The intended implementation is generated by the
    // `implemented_javascript_parser_hooks` attribute.
    // If we end up here, it usually means the attribute was forgotten.
    if cfg!(debug_assertions) {
      panic!(
        "`implemented_hooks` must be generated by the `implemented_javascript_parser_hooks` macro (attribute). \
Please annotate your `impl<'p, 'a> JavascriptParserPlugin<'p, 'a> for ...` block with `#[rspack_plugin_javascript::implemented_javascript_parser_hooks]` \
(or `#[rspack_macros::implemented_javascript_parser_hooks]` inside the repository)."
      );
    }

    // Production fallback: assume the plugin may implement any hook.
    JavascriptParserPluginHooks::all()
  }

  /// Return:
  /// - `Some(true)` signifies the termination of the current
  ///   statement's visit during the pre-walk phase.
  /// - Other return values imply that the walk operation ought to continue
  fn pre_statement(&self, _parser: &mut JavascriptParser<'p>, _stmt: Statement) -> Option<bool> {
    None
  }

  fn block_pre_statement(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _stmt: Statement,
  ) -> Option<bool> {
    None
  }

  /// The return value will have no effect.
  fn top_level_await_expr(&self, _parser: &mut JavascriptParser<'p>, _expr: AwaitExpression) {}

  /// The return value will have no effect.
  fn top_level_for_of_await_stmt(&self, _parser: &mut JavascriptParser<'p>, _stmt: ForOfStatement) {
  }

  fn can_rename(&self, _parser: &mut JavascriptParser<'p>, _str: &str) -> Option<bool> {
    None
  }

  fn rename(&self, _parser: &mut JavascriptParser<'p>, _expr: Expr, _str: &str) -> Option<bool> {
    None
  }

  fn program(&self, _parser: &mut JavascriptParser<'p>, _ast: Program) -> Option<bool> {
    None
  }

  fn statement(&self, _parser: &mut JavascriptParser<'p>, _stmt: Statement) -> Option<bool> {
    None
  }

  /// Called for statements after a terminating point (when only function
  /// declarations should still be processed). Plugins may eliminate or
  /// transform such unused statements.
  ///
  /// Return:
  /// - `Some(true)` means the statement is fully handled and should be skipped
  /// - Other values mean the parser should still walk the statement
  fn unused_statement(&self, _parser: &mut JavascriptParser<'p>, _stmt: Statement) -> Option<bool> {
    None
  }

  fn module_declaration(&self, _parser: &mut JavascriptParser<'p>, _decl: Stmt) -> Option<bool> {
    None
  }

  /// Return:
  /// `None` means continue this `ModuleDecl`
  /// Others means skip this.
  ///
  /// This is similar `hooks.block_pre_statement` in webpack
  fn block_pre_module_declaration(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _decl: Stmt,
  ) -> Option<bool> {
    None
  }

  fn pre_declarator(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _declarator: VariableDeclarator,
    _declaration: VariableDeclaration,
  ) -> Option<bool> {
    None
  }

  fn evaluate(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _expr: Expr,
  ) -> Option<BasicEvaluatedExpression<'p>> {
    None
  }

  fn evaluate_typeof(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _expr: UnaryExpression,
    _for_name: &str,
  ) -> Option<BasicEvaluatedExpression<'p>> {
    None
  }

  fn evaluate_binary_expression(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _expr: BinaryExpression,
    _left: &BasicEvaluatedExpression<'p>,
  ) -> Option<BasicEvaluatedExpression<'p>> {
    None
  }

  fn evaluate_identifier(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _for_name: &str,
    _member_expr_info: Option<&ExpressionExpressionInfo>,
    _start: u32,
    _end: u32,
  ) -> Option<BasicEvaluatedExpression<'p>> {
    None
  }

  /// Evaluate CallExpression when callee is an Identifier (e.g. String(), Number()).
  /// Mirrors webpack's hooks.evaluateCallExpression.
  fn evaluate_call_expression(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _name: &str,
    _expr: CallExpression,
  ) -> Option<BasicEvaluatedExpression<'p>> {
    None
  }

  fn evaluate_call_expression_member(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _property: &str,
    _expr: CallExpression,
    _param: BasicEvaluatedExpression<'p>,
  ) -> Option<BasicEvaluatedExpression<'p>> {
    None
  }

  fn can_collect_destructuring_assignment_properties(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _expr: Expr,
  ) -> Option<bool> {
    None
  }

  fn pattern(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _ident: BindingIdentifier,
    _for_name: &str,
  ) -> Option<bool> {
    None
  }

  fn call(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _expr: CallExpression,
    _for_name: &str,
  ) -> Option<bool> {
    None
  }

  fn call_member_chain(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _expr: CallExpression,
    _for_name: &str,
    _members: &[Atom],
    _members_optionals: &[bool],
    _member_ranges: &[Span],
  ) -> Option<bool> {
    None
  }

  fn member(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _expr: HookMemberExpression,
    _for_name: &str,
  ) -> Option<bool> {
    None
  }

  fn member_chain(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _expr: HookMemberExpression,
    _for_name: &str,
    _members: &[Atom],
    _members_optionals: &[bool],
    _member_ranges: &[Span],
  ) -> Option<bool> {
    None
  }

  fn unhandled_expression_member_chain(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _root_info: &ExportedVariableInfo,
    _expr: HookMemberExpression,
  ) -> Option<bool> {
    None
  }

  #[allow(clippy::too_many_arguments)]
  fn member_chain_of_call_member_chain(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _member_expr: MemberExpression,
    _callee_members: &[Atom],
    _call_expr: CallExpression,
    _members: &[Atom],
    _member_ranges: &[Span],
    _for_name: &str,
  ) -> Option<bool> {
    None
  }

  #[allow(clippy::too_many_arguments)]
  fn call_member_chain_of_call_member_chain(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _call_expr: CallExpression,
    _callee_members: &[Atom],
    _inner_call_expr: CallExpression,
    _members: &[Atom],
    _member_ranges: &[Span],
    _for_name: &str,
  ) -> Option<bool> {
    None
  }

  fn r#typeof(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _expr: UnaryExpression,
    _for_name: &str,
  ) -> Option<bool> {
    None
  }

  /// Return:
  /// - `None` means should walk left and right;
  /// - `Some(true)` means should walk right;
  /// - `Some(false)` means nothing need to do.
  fn expression_logical_operator(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _expr: LogicalExpression,
  ) -> Option<KeepRight> {
    None
  }

  /// Return:
  /// - `None` means should walk left and right;
  fn binary_expression(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _expr: BinaryExpression,
  ) -> Option<bool> {
    None
  }

  /// Return:
  /// - `None` means need walk `stmt.test`, `stmt.cons` and `stmt.alt`;
  /// - `Some(true)` means only need walk `stmt.cons`;
  /// - `Some(false)` means only need walk `stmt.alt`;
  fn statement_if(&self, _parser: &mut JavascriptParser<'p>, _expr: IfStatement) -> Option<bool> {
    None
  }

  fn class_extends_expression(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _super_class: Expr,
    _class_decl_or_expr: ClassDeclOrExpr,
  ) -> Option<bool> {
    None
  }

  fn class_body_element(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _element: ClassElement,
    _class_decl_or_expr: ClassDeclOrExpr,
  ) -> Option<bool> {
    None
  }

  fn class_body_value(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _element: ClassElement,
    _expr_span: Span,
    _class_decl_or_expr: ClassDeclOrExpr,
  ) -> Option<bool> {
    None
  }

  fn declarator(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _expr: VariableDeclarator,
    _stmt: VariableDeclaration,
  ) -> Option<bool> {
    None
  }

  fn new_expression(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _expr: NewExpression,
    _for_name: &str,
  ) -> Option<bool> {
    None
  }

  fn identifier(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _ident: &Identifier,
    _for_name: &str,
  ) -> Option<bool> {
    None
  }

  fn this(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _expr: ThisExpression,
    _for_name: &str,
  ) -> Option<bool> {
    None
  }

  fn assign(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _expr: AssignmentExpression,
    _ident: &Identifier,
    _for_name: &str,
  ) -> Option<bool> {
    None
  }

  fn assign_member_chain(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _expr: AssignmentExpression,
    _members: &[Atom],
    _member_ranges: &[Span],
    _for_name: &str,
  ) -> Option<bool> {
    None
  }

  fn import_call(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _expr: ImportExpression,
    _import_then: Option<CallExpression>,
    _members: Option<(&[Atom], bool)>,
  ) -> Option<bool> {
    None
  }

  fn meta_property(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _root_name: &Atom,
    _span: Span,
  ) -> Option<bool> {
    None
  }

  fn import(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _statement: ImportDeclaration,
    _source: &str,
  ) -> Option<bool> {
    None
  }

  fn import_specifier(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _statement: ImportDeclaration,
    _source: &Atom,
    _export_name: Option<&Atom>,
    _identifier_name: &Atom,
  ) -> Option<bool> {
    None
  }

  fn export_import(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _statement: ExportImport,
    _source: &Atom,
  ) -> Option<bool> {
    None
  }

  fn export(&self, _parser: &mut JavascriptParser<'p>, _statement: ExportLocal) -> Option<bool> {
    None
  }

  fn export_import_specifier(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _statement: ExportImport,
    _source: &Atom,
    _local_id: Option<&Atom>,
    _export_name: Option<&Atom>,
    _export_name_span: Option<Span>,
  ) -> Option<bool> {
    None
  }

  fn export_specifier(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _statement: ExportLocal,
    _local_id: &Atom,
    _export_name: &Atom,
    _export_name_span: Span,
  ) -> Option<bool> {
    None
  }

  fn export_expression(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _statement: ExportDefaultDeclaration,
    _expr: ExportDefaultExpression,
  ) -> Option<bool> {
    None
  }

  fn optional_chaining(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _expr: ChainExpression,
  ) -> Option<bool> {
    None
  }

  fn expression_conditional_operation(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _expr: ConditionalExpression,
  ) -> Option<bool> {
    None
  }

  fn finish(&self, _parser: &mut JavascriptParser<'p>) -> Option<bool> {
    None
  }

  fn is_pure(&self, _parser: &mut JavascriptParser<'p>, _expr: Expr) -> Option<bool> {
    None
  }

  /* plugin interop methods */

  /**
   * This method is used to interop with other plugins.
   * It will be called in ImportMetaPlugin when processing destructuring of `import.meta`
   */
  fn import_meta_property_in_destructuring(
    &self,
    _parser: &mut JavascriptParser<'p>,
    _property: &DestructuringAssignmentProperty,
  ) -> Option<String> {
    None
  }
}

pub type BoxJavascriptParserPlugin =
  Box<dyn for<'p, 'a> JavascriptParserPlugin<'p, 'a> + Send + Sync>;
