module.exports = [
  {
    name: 'frozen-cache',
  },
  {
    name: 'production-tampered-cache',
    cached: 'changed',
    error: 'integrity mismatch',
  },
  {
    name: 'explicit-frozen-tampered-cache',
    mode: 'development',
    frozen: true,
    cached: 'changed',
    fresh: true,
    error: 'integrity mismatch',
  },
  {
    name: 'development-repairs-cache',
    mode: 'development',
    cached: 'changed',
    expected: 'changed',
  },
  {
    name: 'explicit-unfrozen-repairs-cache',
    frozen: false,
    cached: 'changed',
    expected: 'changed',
  },
  {
    name: 'development-repairs-crlf',
    mode: 'development',
    crlf: true,
  },
  {
    name: 'frozen-rejects-crlf',
    crlf: true,
    error: 'integrity mismatch',
  },
  {
    name: 'frozen-missing-entry',
    locked: false,
    cached: false,
    error: 'has no lockfile entry and lockfile is frozen',
  },
  {
    name: 'frozen-missing-cache',
    cached: false,
    error: 'is missing content in the lockfile cache, but lockfile is frozen',
  },
  {
    name: 'frozen-missing-cache-changed',
    cached: false,
    remote: 'changed',
    error: 'has an outdated lockfile entry, but lockfile is frozen',
  },
  {
    name: 'frozen-disabled-cache',
    cache: false,
  },
  {
    name: 'frozen-disabled-cache-changed',
    cache: false,
    remote: 'changed',
    error: 'has an outdated lockfile entry, but lockfile is frozen',
  },
  {
    name: 'frozen-upgrade-changed',
    upgrade: true,
    remote: 'changed',
    error: 'has an outdated lockfile entry, but lockfile is frozen',
  },
  {
    name: 'frozen-upgrade-content-type',
    upgrade: true,
    contentType: 'text/javascript',
    error: 'has an outdated lockfile entry, but lockfile is frozen',
  },
  {
    name: 'unfrozen-upgrade',
    frozen: false,
    upgrade: true,
    remote: 'changed',
    expected: 'changed',
  },
  {
    name: 'frozen-not-modified',
    upgrade: true,
    status: 304,
    requests: [['module.js', '"original"']],
  },
  {
    name: 'frozen-metadata-refresh',
    upgrade: true,
  },
  {
    name: 'frozen-cached-redirect',
    resolved: 'target.js',
  },
  {
    name: 'legacy-frozen-cached-redirect',
    lockAt: 'target.js',
    resolved: 'target.js',
    redirect: 'target.js',
    requests: [['module.js', undefined]],
  },
  {
    name: 'legacy-frozen-tampered-cache',
    lockAt: 'target.js',
    resolved: 'target.js',
    redirect: 'target.js',
    cached: 'changed',
    error: 'integrity mismatch',
  },
  {
    name: 'legacy-frozen-disabled-cache',
    lockAt: 'target.js',
    resolved: 'target.js',
    redirect: 'target.js',
    cache: false,
  },
  {
    name: 'legacy-frozen-disabled-cache-changed',
    lockAt: 'target.js',
    resolved: 'target.js',
    redirect: 'target.js',
    cache: false,
    remote: 'changed',
    error: 'has an outdated lockfile entry, but lockfile is frozen',
  },
  {
    name: 'legacy-frozen-missing-cache',
    lockAt: 'target.js',
    resolved: 'target.js',
    redirect: 'target.js',
    cached: false,
    error: 'is missing content in the lockfile cache, but lockfile is frozen',
  },
  {
    name: 'legacy-frozen-not-modified',
    lockAt: 'target.js',
    resolved: 'target.js',
    redirect: 'target.js',
    upgrade: true,
    status: 304,
    requests: [
      ['module.js', undefined],
      ['target.js', '"original"'],
    ],
  },
  {
    name: 'legacy-frozen-unlocked-target',
    lockAt: 'target.js',
    resolved: 'target.js',
    redirect: 'other.js',
    error: 'has no lockfile entry and lockfile is frozen',
  },
  {
    name: 'legacy-frozen-multiple-redirects',
    lockAt: 'target.js',
    resolved: 'target.js',
    redirect: ['intermediate.js', 'target.js'],
    requests: [
      ['module.js', undefined],
      ['intermediate.js', undefined],
    ],
  },
  {
    name: 'legacy-frozen-disallowed-redirect',
    lockAt: 'target.js',
    resolved: 'target.js',
    redirect: 'http://blocked.example/target.js',
    requests: [['module.js', undefined]],
    error: "doesn't match the allowedUris policy after redirect",
  },
  {
    name: 'legacy-frozen-disallowed-protocol',
    lockAt: 'target.js',
    resolved: 'target.js',
    redirect: 'ftp://integrity.example/target.js',
    requests: [['module.js', undefined]],
    error: 'Redirected URL uses disallowed protocol',
  },
  {
    name: 'legacy-frozen-redirect-limit',
    lockAt: 'target.js',
    resolved: 'target.js',
    redirect: ['one.js', 'two.js', 'three.js', 'four.js', 'five.js', 'target.js'],
    error: 'Too many redirects',
  },
  {
    name: 'legacy-frozen-shared-redirect-limit',
    lockAt: 'target.js',
    resolved: 'target.js',
    redirect: ['one.js', 'two.js', 'three.js', 'four.js', 'target.js', 'other.js'],
    upgrade: true,
    requests: [
      ['module.js', undefined],
      ['one.js', undefined],
      ['two.js', undefined],
      ['three.js', undefined],
      ['four.js', undefined],
      ['target.js', '"original"'],
    ],
    error: 'Too many redirects',
  },
  {
    name: 'legacy-frozen-redirect-no-cache',
    lockAt: 'target.js',
    resolved: 'target.js',
    redirect: 'target.js',
    redirectNoCache: true,
    error: 'has a lockfile entry and is no-cache now, but lockfile is frozen',
  },
  {
    name: 'legacy-frozen-original-not-modified',
    lockAt: 'target.js',
    resolved: 'target.js',
    status: 304,
    requests: [['module.js', undefined]],
    error: 'Request failed with status: 304',
  },
  {
    name: 'frozen-redirect-not-modified',
    resolved: 'target.js',
    redirect: 'target.js',
    upgrade: true,
    status: 304,
    requests: [
      ['module.js', undefined],
      ['target.js', '"original"'],
    ],
  },
  {
    name: 'frozen-multiple-redirects-not-modified',
    resolved: 'target.js',
    redirect: ['intermediate.js', 'target.js'],
    upgrade: true,
    status: 304,
    requests: [
      ['module.js', undefined],
      ['intermediate.js', undefined],
      ['target.js', '"original"'],
    ],
  },
  {
    name: 'frozen-original-not-modified',
    resolved: 'target.js',
    upgrade: true,
    status: 304,
    requests: [['module.js', undefined]],
    error: 'Request failed with status: 304',
  },
  {
    name: 'frozen-redirect-changed-content',
    resolved: 'target.js',
    redirect: 'target.js',
    remote: 'changed',
    upgrade: true,
    error: 'has an outdated lockfile entry, but lockfile is frozen',
  },
  {
    name: 'frozen-redirect-changed-location',
    resolved: 'target.js',
    redirect: 'other.js',
    upgrade: true,
    requests: [
      ['module.js', undefined],
      ['other.js', undefined],
    ],
    error: 'has an outdated lockfile entry, but lockfile is frozen',
  },
  {
    name: 'unfrozen-new-redirect',
    locked: false,
    cached: false,
    frozen: false,
    redirect: 'target.js',
  },
  {
    name: 'frozen-content-to-no-cache',
    upgrade: true,
    noCache: true,
    error: 'has a lockfile entry and is no-cache now, but lockfile is frozen',
  },
  {
    name: 'frozen-no-cache-to-content',
    locked: 'no-cache',
    cached: false,
    error: 'used to have no-cache lockfile entry and has content now, but lockfile is frozen',
  },
  {
    name: 'unfrozen-no-cache-needs-upgrade',
    frozen: false,
    locked: 'no-cache',
    cached: false,
    error: 'upgrading is not enabled',
  },
  {
    name: 'unfrozen-no-cache-upgrade',
    frozen: false,
    upgrade: true,
    locked: 'no-cache',
    cached: false,
  },
  {
    name: 'frozen-no-cache',
    locked: 'no-cache',
    cached: false,
    noCache: true,
  },
  {
    name: 'frozen-ignore',
    locked: 'ignore',
    cached: false,
    remote: 'changed',
    expected: 'changed',
  },
  {
    name: 'unfrozen-new-no-cache',
    locked: false,
    cached: false,
    frozen: false,
    noCache: true,
  },
  {
    name: 'frozen-invalid-lockfile',
    invalidLockfile: true,
    error: 'EOF while parsing',
  },
  {
    name: 'unfrozen-invalid-lockfile',
    frozen: false,
    invalidLockfile: true,
    error: 'EOF while parsing',
  },
];
