const ids = [
	require("./a?0"),
	require("./a?1"),
	require("./a?2"),
	require("./a?3"),
	require("./a?4"),
	require("./a?5"),
	require("./a?6"),
	require("./a?7"),
	require("./a?8"),
	require("./a?9"),
	require("./a?10"),
	require("./a?11"),
	require("./a?12"),
	require("./a?13"),
	require("./a?14"),
	require("./a?15"),
	require("./a?16"),
	require("./a?17"),
	require("./a?18"),
	require("./a?19"),
	require("./a?20"),
	require("./a?21"),
	require("./a?22"),
	require("./a?23"),
	require("./a?24"),
	require("./a?25"),
	require("./a?26"),
	require("./a?27"),
	require("./a?28"),
	require("./a?29"),
	require("./a?30"),
	require("./a?31"),
	require("./a?32"),
	require("./a?33"),
	require("./a?34"),
	require("./a?35"),
	require("./a?36"),
	require("./a?37"),
	require("./a?38"),
	require("./a?39"),
	require("./a?40"),
	require("./a?41"),
	require("./a?42"),
	require("./a?43"),
	require("./a?44"),
	require("./a?45"),
	require("./a?46"),
	require("./a?47"),
	require("./a?48"),
	require("./a?49"),
	require("./a?50"),
	require("./a?51"),
	require("./a?52"),
];

it("should extend compat-hashed module ids only when shorter prefixes collide", () => {
	expect(new Set(ids).size).toBe(ids.length);
	expect(ids.some(id => id.length === 1)).toBe(true);
	expect(ids.some(id => id.length > 1)).toBe(true);
	for (const id of ids) {
		expect(id).toMatch(/^[A-Za-z][A-Za-z0-9]*$/);
	}
});
