[package]
description       = "rspack glob tests"
edition.workspace = true
license           = "MIT"
name              = "rspack_glob_test"
publish           = false
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true

[dev-dependencies]
async-trait  = { workspace = true }
rspack_fs    = { workspace = true }
rspack_glob  = { workspace = true, features = ["fs"] }
rspack_paths = { workspace = true }
smallvec     = { workspace = true }
tokio        = { workspace = true, features = ["macros"] }

[lints]
workspace = true
