//! @generated by `build.rs` from the workspace `Cargo.toml` and `package.json`. Do not edit by hand.
/// The version of the `swc_core` package used in the current workspace.
pub const fn rspack_swc_core_version() -> &'static str {
  "71.0.1"
}

/// The version of the JavaScript `@rspack/core` package.
pub const fn rspack_pkg_version() -> &'static str {
  "2.1.0-rc.0"
}

/// The version of the Rust workspace in the root `Cargo.toml` of the repository.
pub const fn rspack_workspace_version() -> &'static str {
  "0.101.0-rc.0"
}
