[package]
description       = "Rspack glob matching with resumable prefix matching"
edition.workspace = true
license.workspace = true
name              = "rspack_glob"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true

[features]
default = []
fs      = ["dep:async-recursion", "dep:rspack_error", "dep:rspack_fs", "dep:rspack_paths", "dep:rspack_util"]

[dependencies]
async-recursion = { workspace = true, optional = true }
cow-utils       = { workspace = true }
rspack_error    = { workspace = true, optional = true }
rspack_fs       = { workspace = true, optional = true }
rspack_paths    = { workspace = true, optional = true }
rspack_util     = { workspace = true, optional = true }
rustc-hash      = { workspace = true, features = ["std"] }
smallvec        = { workspace = true }

[lints]
workspace = true
