import { value } from './file';

const fs = __non_webpack_require__('fs');
const path = __non_webpack_require__('path');

it("should not change content of html file which generated by html-rspack-plugin", (done) => {
	expect(value).toBe(0);
	const original = fs.readFileSync(path.resolve(__dirname, './index.html'), 'utf-8');
	NEXT(require("../../update")(done, true, () => {
		expect(value).toBe(1);
		const updated = fs.readFileSync(path.resolve(__dirname, './index.html'), 'utf-8');
		expect(original).toEqual(updated);
		done();
	}));
});

module.hot.accept("./file");
