import "./custom-name-tpl";
import "./ignore-es-component";
import "./ignore-style-component";
import "./no-default";
import "./style-css";
import "./style-library";
import "./style-tpl";
import "./style-true";
import "./legacy-babel-plugin-import";
