it("css modules localIdentName with path", () => {
	const style = require("./index.css");
	expect(style).toEqual({
		"#": "-index__# ",
		"##": "-index__## ",
		"#.#.#": "-index__#-#-# ",
		"#fake-id": "-index__#fake-id ",
		"++++++++++[>+++++++>++++++++++>+++>+<<<<-]>++.>+.+++++++..+++.>++.<<+++++++++++++++.>.+++.------.--------.>+.>.":
			"-index__++++++++++[-+++++++-++++++++++-+++-+-----]-++--+-+++++++--+++--++---+++++++++++++++---+++------------------+--- ",
		"-a-b-c-": "-index__-a-b-c- ",
		"-a0-34a___f": "-index__-a0-34a___f ",
		".": "-index__- ",
		123: "-index__123 ",
		"1a2b3c": "-index__1a2b3c ",
		":)": "-index__-) ",
		":`(": "-index__-`( ",
		":hover": "-index__-hover ",
		":hover:focus:active": "-index__-hover-focus-active ",
		"<><<<>><>": "-index__--------- ",
		"<p>": "-index__-p- ",
		"?": "-index__- ",
		"@": "-index__@ ",
		"B&W?": "-index__B&W- ",
		"[attr=value]": "-index__[attr=value] ",
		_: "-index___ ",
		_test: "-index___test ",
		className: "-index__className ",
		"f!o!o": "-index__f!o!o ",
		"f'o'o": "-index__f'o'o ",
		"f*o*o": "-index__f-o-o ",
		"f+o+o": "-index__f+o+o ",
		"f/o/o": "-index__f-o-o ",
		"f\\o\\o": "-index__f-o-o ",
		"foo.bar": "-index__foo-bar ",
		"foo/bar": "-index__foo-bar ",
		"foo/bar/baz": "-index__foo-bar-baz ",
		"foo\\bar": "-index__foo-bar ",
		"foo\\bar\\baz": "-index__foo-bar-baz ",
		"f~o~o": "-index__f~o~o ",
		"m_x_@": "-index__m_x_@ ",
		someId: "-index__someId ",
		subClass: "-index__subClass ",
		test: "-index__test ",
		"{}": "-index__{} ",
		"©": "-index__© ",
		"“‘’”": "-index__“‘’” ",
		"⌘⌥": "-index__⌘⌥ ",
		"☺☃": "-index__☺☃ ",
		"♥": "-index__♥ ",
		"𝄞♪♩♫♬": "-index__𝄞♪♩♫♬ ",
		"💩": "-index__💩 ",
		"😍": "-index__😍 "
	});
});
