name: CI-Dylint

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '.github/workflows/ci-dylint.yaml'
      - '.github/actions/rustup/**'
      - 'crates/**'
      - 'linting/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'rust-toolchain.toml'
  merge_group:
    types: [checks_requested]
  workflow_dispatch:
  push:
    branches:
      - main
      - v1.x
    paths:
      - '.github/workflows/ci-dylint.yaml'
      - '.github/actions/rustup/**'
      - 'crates/**'
      - 'linting/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'rust-toolchain.toml'
    tags-ignore:
      - '**'

jobs:
  dylint:
    name: Dylint
    runs-on: ${{ fromJSON(vars.LINUX_SELF_HOSTED_RUNNER_LABELS || '"ubuntu-22.04"') }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Rust Toolchain
        uses: ./.github/actions/rustup
        with:
          save-if: true
          key: dylint

      - name: Run Cargo codegen
        run: cargo codegen

      - name: Install Dylint Toolchain
        run: rustup toolchain install nightly-2025-10-31 -c rustc-dev -c llvm-tools-preview -c rust-src

      - name: Install cargo-dylint
        run: cargo install cargo-dylint dylint-link --locked

      - name: Run dylint
        run: cargo dylint --all
