name: CI-Lint

on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:
  push:
    branches:
      - main
      - v1.x
    tags-ignore:
      - '**'
jobs:
  lint:
    name: Lint and format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Pnpm Setup
        uses: ./.github/actions/pnpm/setup

      - name: Pnpm Install
        run: pnpm i

      - name: Lint js
        run: pnpm run lint-ci:js

      - name: Prettier
        run: pnpm run format-ci:js

      - name: Check Dependency Version
        run: pnpm run check-dependency-version

      - name: Website Spell Check
        run: pnpm --dir website run check:spell

      - name: Typos Check
        uses: crate-ci/typos@cf5f1c29a8ac336af8568821ec41919923b05a83 # v1.45.1
        with:
          files: .
