name: CI-Lint

on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:
  push:
    branches:
      - main
      - v1.x
    tags-ignore:
      - '**'
jobs:
  lint:
    name: Lint and format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Pnpm Setup
        uses: ./.github/actions/pnpm/setup

      - name: Pnpm Install
        uses: ./.github/actions/pnpm/install-dependencies

      - name: Lint js
        run: |
          pnpm run lint-ci:js
          pnpm run lint:type

      - name: Prettier
        run: pnpm run format-ci:js

      - name: Check Dependency Version
        run: pnpm run check-dependency-version

      - name: Website Spell Check
        run: pnpm --dir website run check:spell

      - name: Typos Check
        uses: crate-ci/typos@bb4666ad77b539a6b4ce4eda7ebb6de553704021 # v1.42.0
        with:
          files: .
