name: CI-Lint

on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:
  push:
    branches:
      - main
      - v1.x
    paths-ignore:
      - '**/*.md'
      - 'website/**'
    tags-ignore:
      - '**'
jobs:
  check-changed:
    runs-on: ubuntu-latest
    name: Check Source Changed
    outputs:
      code_changed: ${{ steps.filter.outputs.code_changed == 'true' }}
      document_changed: ${{ steps.filter.outputs.document_changed == 'true' }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: filter
        with:
          predicate-quantifier: 'every'
          filters: |
            code_changed:
              - "!**/*.md"
              - "!**/*.mdx"
              - "!website/**"
            document_changed:
              - "website/**"

  lint:
    name: Lint and format
    runs-on: ubuntu-latest
    needs: [check-changed]
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Pnpm Setup
        uses: ./.github/actions/pnpm/setup

      - name: Pnpm Install
        uses: ./.github/actions/pnpm/install-dependencies

      - name: Lint js
        if: ${{ needs.check-changed.outputs.code_changed == 'true' }}
        run: pnpm run lint-ci:js

      - name: Prettier
        run: pnpm run format-ci:js

      - name: Lint type
        if: ${{ needs.check-changed.outputs.code_changed == 'true' }}
        run: pnpm run lint:type

      - name: Check Dependency Version
        run: pnpm run check-dependency-version

      - name: Website Spell Check
        if: ${{ needs.check-changed.outputs.document_changed == 'true' }}
        run: pnpm --dir website run check:spell

  spell:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: crate-ci/typos@bb4666ad77b539a6b4ce4eda7ebb6de553704021 # v1.42.0
        with:
          files: .

  pnpm_lockfile_check:
    name: Pnpm Lockfile Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Pnpm Setup
        uses: ./.github/actions/pnpm/setup

      - name: Pnpm Install
        uses: ./.github/actions/pnpm/install-dependencies
        with:
          frozen-lockfile: true
  lint_required_check:
    # this job will be used for GitHub actions to determine required job success or not;
    # When code changed, it will check if any of the test jobs failed.
    # When *only* doc changed, it will run as success directly
    name: Lint Required Check
    needs: [lint, check-changed, spell, pnpm_lockfile_check]
    if: ${{ always() && !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo ${{ join(needs.*.result, ',') }}
      - name: Lint check
        if: ${{ needs.lint.result != 'success' }}
        run: echo "Lint Failed" && exit 1
