name: Ecosystem CI

on:
  push:
    branches:
      - main
      - v1.x
    paths-ignore:
      - '**/*.md'
      - 'website/**'
    tags-ignore:
      - '**'

  workflow_dispatch:
    inputs:
      pr:
        type: number
        description: 'Run ecosystem CI on PR number'
        required: true
      suite:
        description: 'testsuite to run. runs all test suites when `-`.'
        required: false
        type: choice
        options:
          - '-'
          - modernjs
          - rspress
          - rsbuild
          - rslib
          - rstest
          - rsdoctor
          - examples
          - devserver
          - plugin
          - lynx-stack
          - rsbuild-rsc-plugin
      suiteRefType:
        description: 'type of suite ref to use'
        required: true
        type: choice
        options:
          - precoded
          - branch
          - tag
          - commit
        default: 'precoded'
      suiteRef:
        description: 'suite ref to use'
        required: true
        type: string
        default: 'precoded'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  changes:
    runs-on: ubuntu-latest
    if: github.repository == 'web-infra-dev/rspack' && github.event_name != 'workflow_dispatch'
    outputs:
      changed: ${{ steps.changes.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 1
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: changes
        with:
          predicate-quantifier: 'every'
          filters: |
            changed:
              - "!**/*.md"
              - "!**/*.mdx"
              - "!website/**"

  ecosystem_ci_dispatch:
    name: Dispatch ecosystem CI
    runs-on: ubuntu-latest
    if: github.repository == 'web-infra-dev/rspack' && github.event_name == 'workflow_dispatch'
    steps:
      - name: Get PR info
        id: pr-info
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.inputs.pr }},
            });
            core.setOutput('branch', pr.head.ref);
            core.setOutput('repo', pr.head.repo.full_name);

      - name: Trigger Ecosystem CI
        uses: rstackjs/rstack-ecosystem-ci/.github/actions/ecosystem_ci_dispatch@v0.3.0
        with:
          github-token: ${{ secrets.REPO_RSTACK_ECO_CI_GITHUB_TOKEN }}
          ecosystem-owner: web-infra-dev
          ecosystem-repo: rspack
          workflow-file: rspack-ecosystem-ci-from-pr.yml
          pr-number: ${{ github.event.inputs.pr }}
          client-payload: '{"prNumber":"${{ github.event.inputs.pr }}","branchName":"${{ steps.pr-info.outputs.branch }}","repo":"${{ steps.pr-info.outputs.repo }}","suite":"${{ github.event.inputs.suite || ''-'' }}","suiteRefType":"${{ github.event.inputs.suiteRefType }}","suiteRef":"${{ github.event.inputs.suiteRef }}"}'
          branch: ${{ steps.pr-info.outputs.branch }}

  ecosystem_ci_per_commit:
    name: Run ecosystem CI per commit
    needs: changes
    runs-on: ubuntu-latest
    if: github.repository == 'web-infra-dev/rspack' && github.event_name != 'workflow_dispatch' && needs.changes.outputs.changed == 'true'
    steps:
      - name: Trigger Ecosystem CI
        uses: rstackjs/rstack-ecosystem-ci/.github/actions/ecosystem_ci_per_commit@v0.3.0
        with:
          github-token: ${{ secrets.REPO_RSTACK_ECO_CI_GITHUB_TOKEN }}
          ecosystem-owner: web-infra-dev
          ecosystem-repo: rspack
          workflow-file: rspack-ecosystem-ci-from-commit.yml
          client-payload: '{"commitSHA":"${{ github.sha }}","updateComment":true,"repo":"web-infra-dev/rspack","suite":"-","suiteRefType":"precoded","suiteRef":"precoded"}'
