name: Issue Close Require

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  issue-close-require:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    if: github.repository_owner == 'web-infra-dev'
    steps:
      - name: Close inactive need reproduction issues
        uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10.3.0
        with:
          days-before-stale: -1
          days-before-pr-close: -1
          days-before-issue-close: 14
          stale-issue-label: 'need reproduction'
          remove-issue-stale-when-updated: false
          close-issue-message: |
            Since the issue was labeled with `need reproduction`, but no response in 14 days. This issue will be closed. Feel free to comment and reopen it if you have any further questions.

      - name: Close inactive need more info issues
        uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10.3.0
        with:
          days-before-stale: -1
          days-before-pr-close: -1
          days-before-issue-close: 14
          stale-issue-label: 'need more info'
          close-issue-message: |
            Since the issue was labeled with `need more info`, but no response in 14 days. This issue will be closed. Feel free to comment and reopen it if you have any further questions.

      - name: Close inactive awaiting feedback issues
        uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10.3.0
        with:
          days-before-stale: -1
          days-before-pr-close: -1
          days-before-issue-close: 14
          stale-issue-label: 'awaiting more feedback'
          close-issue-message: |
            Since the issue was labeled with `awaiting more feedback`, but no response in 14 days. This issue will be closed. Feel free to comment and reopen it if you have any further questions.
