name: Release Debug

on:
  workflow_dispatch:
    inputs:
      commit:
        required: true
        type: string
        description: 'Commit SHA'
  workflow_run:
    workflows: ['Release Full']
    types:
      - completed
permissions:
  # To publish packages with provenance
  id-token: write
  # Allow commenting on issues for `reusable-build.yml`
  issues: write

jobs:
  release_debug:
    name: Release Debug
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/reusable-release-npm.yml
    with:
      release_type: debug
      ref: ${{ inputs.commit || github.event.workflow_run.head_sha }}
      profile: debug
      test: false
      tag: latest
      tag_confirm: latest
      dry_run: false
      push_tags: false
