name: Binary Size Limit

on:
  workflow_call:

permissions:
  # Allow commenting on Pull Requests
  pull-requests: write

jobs:
  size-limit:
    name: Binding Size Limit
    runs-on: ${{ fromJSON(vars.LINUX_SELF_HOSTED_RUNNER_LABELS || '"ubuntu-22.04"') }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Download binding artifact
        uses: ./.github/actions/artifact/download
        with:
          name: bindings-x86_64-unknown-linux-gnu
          path: crates/node_binding/

      # ci profile builds with strip=false, strip here for accurate size comparison
      - name: Strip binary
        run: strip crates/node_binding/rspack.linux-x64-gnu.node

      - name: Binary Size-limit
        uses: ./.github/actions/binary-limit
        with:
          # 50k 50*1024
          size-threshold: ${{ vars.SIZE_LIMIT_THRESHOLD || 51200 }}
