name: Binary Size Limit

on:
  workflow_call:

permissions:
  # Allow commenting on Pull Requests
  pull-requests: write

jobs:
  size-limit:
    name: Binding Size Limit
    runs-on: ${{ fromJSON(vars.LINUX_SELF_HOSTED_RUNNER_LABELS || '"ubuntu-22.04"') }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Download binding artifact
        uses: ./.github/actions/artifact/download
        with:
          name: bindings-x86_64-unknown-linux-gnu
          path: crates/node_binding/

      - name: Binary Size-limit
        uses: ./.github/actions/binary-limit
        with:
          # 50k 50*1024
          size-threshold: ${{ vars.SIZE_LIMIT_THRESHOLD || 51200 }}
