module.exports = {
	findBundle() {
		return ['index.mjs']
	},
	snapshotFileFilter(file) {
		return (
			(file.endsWith('.mjs') || file.endsWith('.js') || file.endsWith('.css')) &&
			!file.includes('runtime.js')
		);
	},
	// Strip the decorative `/*!*** path ***!*/` banner comments generated by
	// css-loader. Their border width depends on the absolute pnpm store path
	// which differs across platforms, making snapshots non-portable.
	snapshotContent(content) {
		return content.replace(/\/\*![\s\S]*?\*\/\n?/g, '');
	},
}
